### PR TITLE
Gui: fixes #12540: ‘ModuleShiboken’ was not declared in this scope

### LINKED ISSUE #12540: aed799c breaks build error: ‘ModuleShiboken’ was not declared in this scope
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Gentoo Linux, git code,   shiboken2-5.15.12 

`[ 68%] Building CXX object src/Mod/TechDraw/App/CMakeFiles/TechDraw.dir/TechDraw_autogen/mocs_compilation.cpp.o
/home/cory/sources/freecad-source/src/Gui/PythonWrapper.cpp: In function ‘PyObject* Gui::importShiboken()’:
/home/cory/sources/freecad-source/src/Gui/PythonWrapper.cpp:433:43: error: ‘ModuleShiboken’ was not declared in this scope
  433 |     PyObject* obj = PyImport_ImportModule(ModuleShiboken);
      |                                           ^~~~~~~~~~~~~~

`

Git bisect shows failure starts at commit  aed799ce2af62ea214d3ffa525e60ddc72f947a2 

Let me know if I can be of any help. Thanks

### Full version info

```shell
git checkout aed799ce2af62ea214d3ffa525e60ddc72f947a2
```

### Subproject(s) affected?

None

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by wwmayer**
https://forum.freecad.org/viewtopic.php?t=80726

### CODE REVIEW

**Comment by maxwxyz** [comment]
fixes https://github.com/FreeCAD/FreeCAD/issues/12540

**Comment by 3x380V** [comment]
Okay, so it basically reverts commit which removed ModuleShiboken and adds dozen lines of noise. Could that 'linter', whatever that is, be fixed instead?
