### ISSUE TITLE
aed799c breaks build error: ‘ModuleShiboken’ was not declared in this scope

### ISSUE THREAD

**Issue by clytle374** [FreeCAD/FreeCAD#12540]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Gentoo Linux, git code,   shiboken2-5.15.12 

`[ 68%] Building CXX object src/Mod/TechDraw/App/CMakeFiles/TechDraw.dir/TechDraw_autogen/mocs_compilation.cpp.o
/home/cory/sources/freecad-source/src/Gui/PythonWrapper.cpp: In function ‘PyObject* Gui::importShiboken()’:
/home/cory/sources/freecad-source/src/Gui/PythonWrapper.cpp:433:43: error: ‘ModuleShiboken’ was not declared in this scope
  433 |     PyObject* obj = PyImport_ImportModule(ModuleShiboken);
      |                                           ^~~~~~~~~~~~~~

`

Git bisect shows failure starts at commit  aed799ce2af62ea214d3ffa525e60ddc72f947a2 

Let me know if I can be of any help. Thanks

### Full version info

```shell
git checkout aed799ce2af62ea214d3ffa525e60ddc72f947a2
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by clytle374** [comment]
Somehow pyside was turned off in cmake(I didn't know it was now an option to not have it), I turned pyside on and it builds fine now.
And the pressing preferences crash went away as the same time.

So I guess this can be closed.

**Comment by clytle374** [comment]
Build with pyside turned off is verified as fixed.
