### PR TITLE
[Gui] fix compilation error on Ubuntu Linux 18.04

### PR DESCRIPTION
**Pull request by hvfrancesco**
Trying to fix a compilation error on Ubuntu 18.04

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
I think you got it right.. Let's wait for the travis build to finish to make sure

**Comment by hvfrancesco** [comment]
seems this fixes things only with qt versions => 5.4
the build problem I experience was introduced in commit ee912a5f16b2f032a3f716c2c26ae80bf58faa8e

**Comment by vocx-fc** [comment]
@wwmayer ping

**Comment by bgamari** [comment]
FWIW I encountered the same issue and was about to propose the same solution.

**Comment by hvfrancesco** [comment]
maybe something like that?

std::string groupName = stdString(sel->text(0).toLatin1().constData(), sel->text(0).toLatin1().length())

**Comment by WandererFan** [comment]
#include <Base/Tools.h>

std::string groupName = Base::Tools::toStdString(sel->text(0));

**Comment by wwmayer** [comment]
4614eb92a should fix it. Sorry for the trouble.
