### ISSUE TITLE
Macro: `imports FreeCAD as App` but then barfs on using App:Part (works in v0.22)

### ISSUE THREAD

**Issue by KeithSloan** [FreeCAD/FreeCAD#16536]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

MACRO : imports FreeCAD as App but then barfs on using App:Part - works on 0.22[](url)

### Full version info

```shell
Macro and testfiles at https://github.com/KeithSloan/FreeCAD_GDML_Test_Collection

branch : testFC1.0

Macro invoked 

GDMLCOGcalcDirectory.py

Source : test_FC_files
Target : FC_COG's

Fails with 

5:15:46  Init Prompt
15:15:46  Directory Source
15:15:46  Directory Target
15:16:08  Directory Path /Users/keithsloan/MEGA/MEGAsync/CAD_Files/GDML/FreeCAD_GDML_Test_Collection/test_FC_files
15:16:15  Directory Path /Users/keithsloan/MEGA/MEGAsync/CAD_Files/GDML/FreeCAD_GDML_Test_Collection/FC_COGs
15:16:18  
Processing - creating COG calculations for GDML files in directory : /Users/keithsloan/MEGA/MEGAsync/CAD_Files/GDML/FreeCAD_GDML_Test_Collection/test_FC_files to /Users/keithsloan/MEGA/MEGAsync/CAD_Files/GDML/FreeCAD_GDML_Test_Collection/FC_COGs
15:16:18  Process FC file /Users/keithsloan/MEGA/MEGAsync/CAD_Files/GDML/FreeCAD_GDML_Test_Collection/test_FC_files/logical_container_test2.FCStd
15:16:18  Traceback (most recent call last):
15:16:18    File "/Users/keithsloan/Library/Application Support/FreeCAD/Macro/GDMLCOGcalcDirectory.py", line 140, in onCOGcalc
15:16:18      self.processFile(filepath, targetPath)
15:16:18    File "/Users/keithsloan/Library/Application Support/FreeCAD/Macro/GDMLCOGcalcDirectory.py", line 99, in processFile
15:16:18      spec.loader.exec_module(foo)
15:16:18    File "<frozen importlib._bootstrap_external>", line 940, in exec_module
15:16:18    File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
15:16:18    File "/Users/keithsloan/Library/Application Support/FreeCAD/Macro/calcCenterOfMass.py", line 169, in <module>
15:16:18      def topObjects(part: App.Part) -> list:
15:16:18                           ^^^^^^^^
15:16:18  AttributeError: module 'FreeCAD' has no attribute 'Part'
15:27:26  Init Prompt
15:27:26  Directory Source
15:27:26  Directory Target


Works on FC 0.22
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Do you mind linking directly to the macro's source code ?

**Comment by KeithSloan** [comment]
Macro is in Repro mentioned but attaching here
[calcCenterOfMass.py.txt](https://github.com/user-attachments/files/17002846/calcCenterOfMass.py.txt)

**Comment by luzpaz** [comment]
Thanks. Here's the direct link: https://github.com/KeithSloan/FreeCAD_GDML_Test_Collection/blob/main/calcCenterOfMass.py

**Comment by luzpaz** [comment]
@hasecilu would you weigh-in on this ?

**Comment by hasecilu** [comment]
Hi, first time checking this WB?

Probably you meant `Part.Shape` instead of `FreeCAD::Part`. Are we talking about Part objects?

For example in Fasteners wee have:

```py
    def makeHexPrism(width: float, height: float) -> Part.Shape:
```

There is also `Part.Face` and `Part.Wire`.

**Comment by KeithSloan** [comment]
No  We use App::Parts 

![Image 18-09-2024 at 22 36](https://github.com/user-attachments/assets/85ce024b-1185-48c2-8064-f71dad15939e)

```
# Gui.Selection.clearSelection()
>>> # Gui.Selection.addSelection('Unnamed','worldVOL','LV_Box.')
>>> ### Begin command Std_SendToPythonConsole
>>> # try:
>>> #     del(doc,lnk,obj,shp,sub,subs)
>>> # except Exception:
>>> #     pass
>>> # 
>>> # doc = App.getDocument("Unnamed")
>>> # obj = doc.getObject("LV_Box")
>>> ### End command Std_SendToPythonConsole
>>> print(obj.TypeId)
App::Part
>>>
```
Macro works in FC 0.22

**Comment by KeithSloan** [comment]
Try this file with the macro on FC0.20 and FC1.0 RC former works 
[logical_container_test2.FCStd.txt](https://github.com/user-attachments/files/17050846/logical_container_test2.FCStd.txt)

**Comment by hasecilu** [comment]
I'm on 1.0 branch, opened the example, removed "App::Part" from the methods but got this error on RC1 version.

```python
16:13:03  Init Prompt
16:13:03  Directory Source
16:13:03  Directory Target
16:13:07  Directory Path /home/uli/FreeCAD/tests/logicalContainer
Processing - creating COG calculations for GDML files in directory : /home/uli/FreeCAD/tests/logicalContainer to /home/uli/FreeCAD/tests/out
16:13:14  Process FC file /home/uli/FreeCAD/tests/logicalContainer/logical_container_test2.FCStd
16:13:14  Process FC filename logical_container_test2.FCStd filepath /home/uli/FreeCAD/tests/logicalContainer/logical_container_test2.FCStd targetPath /home/uli/FreeCAD/tests/out 
16:13:14  RootObjects len(FreeCAD.ActiveDocument.RootObjects:
16:13:14  Found Root Part : worldVOL
16:13:14   Number of Selections 1
16:13:14  Traceback (most recent call last):
16:13:14    File "/home/uli/.local/share/FreeCAD/Macro/GDMLCOGcalcDirectory.py", line 140, in onCOGcalc
16:13:14      self.processFile(filepath, targetPath)
16:13:14    File "/home/uli/.local/share/FreeCAD/Macro/GDMLCOGcalcDirectory.py", line 124, in processFile
16:13:14      foo.calcCenterOfMass(exportPath)
16:13:14    File "/home/uli/.local/share/FreeCAD/Macro/calcCenterOfMass.py", line 341, in calcCenterOfMass
16:13:14      for part in childObjects[wv]:
16:13:14                  ~~~~~~~~~~~~^^^^
16:13:14  KeyError: <Part object>
```

**Comment by KeithSloan** [comment]
I should have mentioned to run the Macro, you select the Part labelled worldVol and then execute the macro.
Works in 0.22 see the following output that should appear in Report ViewCalc Part CM LV_Box

22:49:44  LV_Box               Volume:   553.97 cm^3 --> center of "mass": (  -0.09,  58.05,  -0.01) mm, moments of inetria: ( 2.465, 0.6795,  2.707) x10^4 cm^5
22:49:44  
22:49:44  Total                Volume:   553.97 cm^3 --> center of "mass": (  -0.09,  58.05,  -0.01) mm, moments of inetria: ( 2.465, 0.6795,  2.707) x10^4 cm^5

We use to check that what gets created on import of the gdml file in Geant4 is the same as FC, so a similar calculation
is done in Geant4 and run a script to compare.

To be sure things are still working with FC 1.0 RC we ideally need to be able to run these checks.

**Comment by KeithSloan** [comment]
The macro's are not in the workbench but https://github.com/KeithSloan/FreeCAD_GDML_Test_Collection
see branch FC 0.20

The repro is all to do with testing the GDML workbench. We need to be able to run the tests if we are to say that the workbench works with FC 1.0 RC

**Comment by KeithSloan** [comment]
Okay I have a workaround

I change the two definitions

def topObjects(part: App.Part) -> list:
to
# def topObjects(part: App.Part) -> list:
def topObjects(part)

def partCM(part: App.Part) -> tuple:
to
# def partCM(part: App.Part) -> tuple:
def partCM(part)

And it works

**Comment by KeithSloan** [comment]
Okay it looks to me with FC 0.20 python was not picking up on the error

def topObjects(part: App.Part) -> list:

Think correct syntax should be

def topObjects(part: App::Part) -> list:

Which also works on FC 0.20 but not FC 1.0 RC

Should be able to declare to a function variables and type, the variable in this case being part and type App::Part

**Comment by luzpaz** [comment]
What is the error message when you try `def topObjects(part: App::Part) -> list:` on 1.0 RC1 ?

**Comment by KeithSloan** [comment]
Actual both FC 0.20 and FC 1.0 RC give syntax error on

**Comment by hasecilu** [comment]
> I should have mentioned to run the Macro, you select the Part labelled worldVol and then execute the macro.
> Works in 0.22 see the following output that should appear in Report ViewCalc Part CM LV_Box

Effectively, I have been doing that, select the Volume and run the macro from the test collection repository, branch `TestFC1.0`. Let's see if other users also have the issue I mentioned.

Can't test on 0.20 and 0.21 because the old AppImages refuse to open.

**Comment by KeithSloan** [comment]
Just became aware of a similar problem where adding the python type in a function call has caused a problem
see https://github.com/KeithSloan/GDML/discussions/143

In this case def addFormulaMaterial(self, compositionDict: dict[str, int]):

Is this a problem with variations of python? FreeCAD and python?

Going to raise in the Forum, so you may close for now.
