### ISSUE TITLE
current git build failure. AppDrawingGuiPy.cpp:113:48: error: expected ‘;’ before ‘{’ 

### ISSUE THREAD

**Issue by clytle374** [FreeCAD/FreeCAD#10156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Full version info

```shell
Building git master on Gentoo Linux
Here is "About Freecad" from a working commit.
[code]
OS: Gentoo Linux (KDE//usr/share/xsessions/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.33727 (Git)
Build type: Unknown
Branch: (no branch, bisect started on 92b26354ba)
Hash: 9587393ca31cf6ee5bb2307630ec89a6eb19c466
Python 3.11.4, Qt 5.15.10, Coin 4.0.0, Vtk , OCC 7.7.0
Locale: English/United States (en_US)
Installed mods: 
  * BOLTSFC
  * kicadStepUpMod 10.19.4
  * fasteners 0.4.59
[/code]
```

### Subproject(s) affected?

None

### Problem description

git bisect says 
`
git bisect bad 
Bisecting: 0 revisions left to test after this (roughly 0 steps)
[33384cff9cdbbb789081c39bbdcd4195aa2ba0bc] [Everywhere] FileInfo::hasExtension for multiple values (#9774)

`
Here is my build failure.  

`[ 76%] Building CXX object src/Mod/Part/Gui/CMakeFiles/PartGui.dir/CommandSimple.cpp.o
[ 76%] Building CXX object src/Mod/Part/Gui/CMakeFiles/PartGui.dir/CommandParametric.cpp.o
[ 76%] Building CXX object src/Mod/ReverseEngineering/Gui/CMakeFiles/ReverseEngineeringGui.dir/Command.cpp.o
/home/cory/sources/freecad-source-testing/src/Mod/Drawing/Gui/AppDrawingGuiPy.cpp: In member function ‘Py::Object DrawingGui::Module::importer(const Py::Tuple&)’:
/home/cory/sources/freecad-source-testing/src/Mod/Drawing/Gui/AppDrawingGuiPy.cpp:113:48: error: expected ‘;’ before ‘{’ token
  113 |         if (file.hasExtension({"svg", "svgz"}) {
      |                                                ^
/home/cory/sources/freecad-source-testing/src/Mod/Drawing/Gui/AppDrawingGuiPy.cpp:123:11: error: expected primary-expression before ‘else’
  123 |         } else {
      |           ^~~~
/home/cory/sources/freecad-source-testing/src/Mod/Drawing/Gui/AppDrawingGuiPy.cpp:123:11: error: expected ‘)’ before ‘else’
/home/cory/sources/freecad-source-testing/src/Mod/Drawing/Gui/AppDrawingGuiPy.cpp:113:12: note: to match this ‘(’
  113 |         if (file.hasExtension({"svg", "svgz"}) {
      |            ^
/home/cory/sources/freecad-source-testing/src/Mod/Drawing/Gui/AppDrawingGuiPy.cpp:127:26: warning: suggest braces around empty body in an ‘if’ statement [-Wempty-body]
  127 |         return Py::None();
      |                          ^
[ 76%] Building CXX object src/Mod/Part/Gui/CMakeFiles/PartGui.dir/CrossSections.cpp.o
/home/cory/sources/freecad-source-testing/src/Mod/Drawing/Gui/AppDrawingGuiPy.cpp:128:5: warning: control reaches end of non-void function [-Wreturn-type]
  128 |     }
      |     ^
make[2]: *** [src/Mod/Drawing/Gui/CMakeFiles/DrawingGui.dir/build.make:381: src/Mod/Drawing/Gui/CMakeFiles/DrawingGui.dir/AppDrawingGuiPy.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 76%] Building CXX object src/Mod/Part/Gui/CMakeFiles/PartGui.dir/Mirroring.cpp.o
`
And my output from cmake
`-- Compiler: GNU, version: 12.2.1
-- prefix: /usr/local
-- bindir: bin
-- datadir: share
-- docdir: share/doc/FreeCAD
-- includedir: include
-- libdir: lib64
-- cmake: 3.26.4
-- Compiling with Qt 5
-- BUILD_MESH_PART requires BUILD_SMESH to be ON, but it is ""
-- BUILD_OPENSCAD requires BUILD_MESH_PART to be ON, but it is "OFF"
-- find_package() was used to locate fmt version 9.1.0
-- PyCXX found:
--   Headers:  /home/cory/sources/freecad-source-testing/src
--   Sources:  /home/cory/sources/freecad-source-testing/src/CXX
--   Version:  7.1.7
-- -- Found OCE/OpenCASCADE version: 7.7.0
-- -- OCE/OpenCASCADE include directory: /usr/include/opencascade
-- -- OCE/OpenCASCADE shared libraries directory: /usr/lib64/opencascade
-- Found Boost: /usr/lib64/cmake/Boost-1.82.0/BoostConfig.cmake (found suitable version "1.82.0", minimum required is "1.65") found components: filesystem program_options regex system thread date_time 
-- Set up to compile with Qt 5.15.10
-- Shiboken2Config: Using default python: -python3.11
-- SHIBOKEN_PYTHON_INCLUDE_DIRS computed to value: '/usr/include/python3.11'
-- SHIBOKEN_PYTHON_LIBRARIES computed to value: ''
-- libshiboken built for RelWithDebInfo
-- PySide 5.15.10 Python module found at /usr/lib/python3.11/site-packages/PySide2.

-- Found Matplotlib: /usr/lib/python3.11/site-packages/matplotlib (found version "3.7.1")
-- Platform is 64-bit, set -D_OCC64
-- [E57] Revison ID: E57Format-2.2.1-x86_64-linux-gcc12
-- [E57] Building static library
-- setting gcc options: -Wall -Werror -Wno-deprecated -pedantic-errors
-- Found Boost: /usr/lib64/cmake/Boost-1.82.0/BoostConfig.cmake (found version "1.82.0") found components: python311 
-- found Boost: 1_82
-- boost-incude dirs are: /usr/include
-- boost-python lib is: 
-- boost_LIBRARY_DIRS is: 
-- Boost_LIBRARIES is: Boost::python
-- area module (for Path Workbench) will be installed to: lib64
-- Performing Test _flag_found
-- Performing Test _flag_found - Success
-- Performing Test _flag_found
-- Performing Test _flag_found - Success
-- Coin3D doc is installed

   ==============
     System
   ==============

-- bindir:                      bin
-- BLAS:                        -undefined-
-- CMAKE_VERSION:               3.26.4
-- Compiler:                    /usr/bin/c++ (12.2.1)
-- datadir:                     share
-- docdir:                      share/doc/FreeCAD
-- includedir:                  include
-- libdir:                      lib64
-- prefix:                      /usr/local
-- Python:                      3.11.4 [/usr/bin/python3.11] Suffix: [-python3.11]

   ==============
     Config
   ==============

-- BUILD_FEM:                   OFF 
-- BUILD_GUI:                   ON
-- BUILD_SMESH:                 -undefined-
-- BUILD_START:                 ON
-- BUILD_TECHDRAW:              ON
-- BUILD_VR:                    OFF 
-- BUILD_WEB:                   ON
-- CMAKE_BUILD_TYPE:            OFF 
-- CMAKE_CXX_FLAGS:             -Wall -Wextra -Wno-write-strings 
-- CMAKE_CXX_STANDARD:          17
-- CMAKE_INSTALL_PREFIX:        /usr/local
-- CMAKE_PREFIX_PATH:           -undefined-
-- ENABLE_DEVELOPER_TESTS:      ON
-- FREECAD_CREATE_MAC_APP:      -undefined-
-- FREECAD_LIBPACK_USE:         OFF 
-- FREECAD_QT_VERSION:          Auto
-- FREECAD_USE_EXTERNAL_KDL:    OFF 
-- FREECAD_USE_EXTERNAL_SMESH:  OFF 
-- FREECAD_USE_FREETYPE:        ON
-- FREECAD_USE_PYBIND11:        OFF 
-- PYTHON_EXECUTABLE:           /usr/bin/python3.11
-- PYTHON_LIBRARY:              /usr/lib64/libpython3.11.so
-- USE_CUDA:                    -undefined-
-- USE_OPENCV:                  -undefined-

   ==============
     Libraries
   ==============

-- Boost:                       1.82.0
-- Coin3D:                      4.0.0 [Coin] [/usr/include/Inventor]
-- Coin3D_DOC:                  not found
-- DesignerPlugin:              not built (BUILD_DESIGNER_PLUGIN is OFF)
-- Doxygen:                     1.9.6 Language: English
-- Eigen3:                      3.4.0
-- fmt:                         9.1.0
-- Freetype:                    2.13.0
-- Matplotlib:                  3.7.1 PathDirs: /usr/lib/python3.11/site-packages/matplotlib
-- NETGEN:                      not enabled
-- OCC:                         7.7.0 [/usr/lib64/opencascade] [/usr/include/opencascade]
-- OCC_Libs:                    [TKFillet;TKMesh;TKernel;TKG2d;TKG3d;TKMath;TKIGES;TKSTL;TKShHealing;TKXSBase;TKBool;TKBO;TKBRep;TKTopAlgo;TKGeomAlgo;TKGeomBase;TKOffset;TKPrim;TKSTEPBase;TKSTEPAttr;TKSTEP209;TKSTEP;TKHLR;TKFeat]
-- OpenGL_Lib:                  [/usr/lib64/libGL.so]
-- OpenGLU_Incl:                [/usr/include]
-- OpenGLU_Lib:                 [/usr/lib64/libGLU.so]
-- pivy:                        0.6.8
-- pybind11:                    not enabled
-- PYCXX:                       7.1.7 Incl: /home/cory/sources/freecad-source-testing/src Src:/home/cory/sources/freecad-source-testing/src/CXX
-- PySide:                      5.15.10 [/usr/include/PySide2]
-- PySideTools:                 v: 2  uic: [/usr/lib64/qt5/bin/uic]  rcc: [/usr/lib64/qt5/bin/rcc]
-- QtConcurrent:                5.15.10
-- QtCore:                      5.15.10
-- QtNetwork:                   5.15.10
-- QtOpenGL:                    5.15.10
-- QtPrintSupport:              5.15.10
-- QtSvg:                       5.15.10
-- QtUiTools:                   5.15.10
-- QtWebEngineWidgets:          5.15.10
-- QtWidgets:                   5.15.10
-- QtXml:                       5.15.10
-- Rift:                        not enabled (BUILD_VR)
-- Shiboken:                    5.15.10 [/usr/include/shiboken2;/usr/include/python3.11]
-- SMESH:                       do not build
-- SPNAV:                       [/usr/lib64/libspnav.so] [/usr/include]
-- SWIG:                        4.0.2
-- XercesC:                     3.2.4 [/usr/lib64/libxerces-c.so] [/usr/include]
-- ZLIB:                        1.2.13

=================================================
Now run 'cmake --build /home/cory/freecad' to build FreeCAD
=================================================

-- Configuring done (2.4s)
-- Generating done (0.9s)
-- Build files have been written to: /home/cory/freecad
` 

### Anything else?

I'll do whatever debugging I can, but may need educated on the process. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by clytle374** [comment]
fixed before i finished report
http://github.com/FreeCAD/FreeCAD/commit/778653825b0b84
thanks, Freecad and all you developers all are great 
Cory
