### PR TITLE
Topo Naming PR 3

### PR DESCRIPTION
**Pull request by realthunder**
Third batch of Topo Naming PR, which provides support of Topo Naming in Sketcher workbench. End user can now test all features from Part workbench. The next and final batch of PR will cover PartDesign workbench, which will take some time, as there are significant changes of PartDesign in my branch that are not directly related to Topo Naming. Besides, it is better to give end users some time to actually test the toponaming branch first. Cheers!

### CODE REVIEW

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7487">pipeline status</a> for feature branch [PR_7487](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7487). Pipeline [639822403](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/639822403) was triggered at [aaa494c](https://github.com/FreeCAD/FreeCAD/pull/7487/commits/aaa494ca495334821e389d941d9c6c8be5acade7). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7487">pipeline status</a> for feature branch [PR_7487](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7487). Pipeline [639826197](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/639826197) was triggered at [02b056b](https://github.com/FreeCAD/FreeCAD/pull/7487/commits/02b056bce91101fc0d3657afbff145bf77029b28). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
Many thanks!
Can you please check the warnings from CLazy?:
https://github.com/FreeCAD/FreeCAD/actions/runs/3051718451/jobs/4920278328

If they are unrelated to your changes, we can ignore them.

**Comment by donovaly** [comment]
To please the spellchecker, I just fixed 2 typos, can you therefore please rebase the PR?

**Comment by berndhahnebach** [comment]
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7487">pipeline status</a> for feature branch [PR_7487](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7487). Pipeline [640656510](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/640656510) was triggered at [c34bf8e](https://github.com/FreeCAD/FreeCAD/pull/7487/commits/c34bf8e91cf7979cae9b2a3749daa04200f69022). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

**Comment by donovaly** [comment]
Thanks for the fixes. Merging now.

I will make the announcement when we have builds.

@luzpaz , the idea is now to make builds for the current toponaming branch and when we have builds for Linux, mac and Win we make the announcement. I will also write you a private message.

**Comment by donovaly** [comment]
I cannot compile the toponaming branch after the merge because of this compilation error:

```
2>ImportOCAF2.cpp
2>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\include\xutility(4145,16): error C2280: 'Import::ImportOCAF2::DocumentInfo &Import::ImportOCAF2::DocumentInfo::operator =(const Import::ImportOCAF2::DocumentInfo &)': attempting to reference a deleted function (compiling source file D:\FreeCADGit\src\Mod\Import\App\AppImportPy.cpp)
2>D:\FreeCADGit\src\Mod\Import\App\ImportOCAF2.h(171): message : compiler has generated 'Import::ImportOCAF2::DocumentInfo::operator =' here (compiling source file D:\FreeCADGit\src\Mod\Import\App\AppImportPy.cpp)
2>D:\FreeCADGit\src\Mod\Import\App\ImportOCAF2.h(171,5): message : 'Import::ImportOCAF2::DocumentInfo &Import::ImportOCAF2::DocumentInfo::operator =(const Import::ImportOCAF2::DocumentInfo &)': function was implicitly deleted because 'Import::ImportOCAF2::DocumentInfo' has a data member 'Import::ImportOCAF2::DocumentInfo::children' of reference type (compiling source file D:\FreeCADGit\src\Mod\Import\App\AppImportPy.cpp)
2>D:\FreeCADGit\src\Mod\Import\App\ImportOCAF2.h(167): message : see declaration of 'Import::ImportOCAF2::DocumentInfo::children' (compiling source file D:\FreeCADGit\src\Mod\Import\App\AppImportPy.cpp)
2>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\include\vector(1314): message : see reference to function template instantiation '_OutIt *std::_Copy_unchecked<_Iter,Import::ImportOCAF2::DocumentInfo*>(_InIt,_InIt,_OutIt)' being compiled
2>        with
2>        [
2>            _OutIt=Import::ImportOCAF2::DocumentInfo *,
2>            _Iter=Import::ImportOCAF2::DocumentInfo *,
2>            _InIt=Import::ImportOCAF2::DocumentInfo *
2>        ] (compiling source file D:\FreeCADGit\src\Mod\Import\App\AppImportPy.cpp)
2>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\include\vector(1337): message : see reference to function template instantiation 'void std::vector<Import::ImportOCAF2::DocumentInfo,std::allocator<Import::ImportOCAF2::DocumentInfo>>::_Assign_range<_Iter>(_Iter,_Iter,std::forward_iterator_tag)' being compiled
2>        with
2>        [
2>            _Iter=Import::ImportOCAF2::DocumentInfo *
2>        ] (compiling source file D:\FreeCADGit\src\Mod\Import\App\AppImportPy.cpp)
2>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\include\vector(1337): message : see reference to function template instantiation 'void std::vector<Import::ImportOCAF2::DocumentInfo,std::allocator<Import::ImportOCAF2::DocumentInfo>>::_Assign_range<_Iter>(_Iter,_Iter,std::forward_iterator_tag)' being compiled
2>        with
2>        [
2>            _Iter=Import::ImportOCAF2::DocumentInfo *
2>        ] (compiling source file D:\FreeCADGit\src\Mod\Import\App\AppImportPy.cpp)
2>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\include\vector(1361): message : see reference to function template instantiation 'void std::vector<Import::ImportOCAF2::DocumentInfo,std::allocator<Import::ImportOCAF2::DocumentInfo>>::assign<Import::ImportOCAF2::DocumentInfo*,0>(_Iter,_Iter)' being compiled
2>        with
2>        [
2>            _Iter=Import::ImportOCAF2::DocumentInfo *
2>        ] (compiling source file D:\FreeCADGit\src\Mod\Import\App\AppImportPy.cpp)
2>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\include\vector(1361): message : see reference to function template instantiation 'void std::vector<Import::ImportOCAF2::DocumentInfo,std::allocator<Import::ImportOCAF2::DocumentInfo>>::assign<Import::ImportOCAF2::DocumentInfo*,0>(_Iter,_Iter)' being compiled
2>        with
2>        [
2>            _Iter=Import::ImportOCAF2::DocumentInfo *
2>        ] (compiling source file D:\FreeCADGit\src\Mod\Import\App\AppImportPy.cpp)
2>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\include\vector(1345): message : while compiling class template member function 'std::vector<Import::ImportOCAF2::DocumentInfo,std::allocator<Import::ImportOCAF2::DocumentInfo>> &std::vector<Import::ImportOCAF2::DocumentInfo,std::allocator<Import::ImportOCAF2::DocumentInfo>>::operator =(const std::vector<Import::ImportOCAF2::DocumentInfo,std::allocator<Import::ImportOCAF2::DocumentInfo>> &)' (compiling source file D:\FreeCADGit\src\Mod\Import\App\AppImportPy.cpp)
2>D:\FreeCADGit\src\Mod\Import\App\ImportOCAF2.h(179): message : see reference to function template instantiation 'std::vector<Import::ImportOCAF2::DocumentInfo,std::allocator<Import::ImportOCAF2::DocumentInfo>> &std::vector<Import::ImportOCAF2::DocumentInfo,std::allocator<Import::ImportOCAF2::DocumentInfo>>::operator =(const std::vector<Import::ImportOCAF2::DocumentInfo,std::allocator<Import::ImportOCAF2::DocumentInfo>> &)' being compiled (compiling source file D:\FreeCADGit\src\Mod\Import\App\AppImportPy.cpp)
2>D:\FreeCADGit\src\Mod\Import\App\ImportOCAF2.h(172): message : see reference to class template instantiation 'std::vector<Import::ImportOCAF2::DocumentInfo,std::allocator<Import::ImportOCAF2::DocumentInfo>>' being compiled (compiling source file D:\FreeCADGit\src\Mod\Import\App\AppImportPy.cpp)
2>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\include\xutility(4145,16): error C2280: 'Import::ImportOCAF2::DocumentInfo &Import::ImportOCAF2::DocumentInfo::operator =(const Import::ImportOCAF2::DocumentInfo &)': attempting to reference a deleted function (compiling source file D:\FreeCADGit\src\Mod\Import\App\ImportOCAF2.cpp)
2>D:\FreeCADGit\src\Mod\Import\App\ImportOCAF2.h(171): message : compiler has generated 'Import::ImportOCAF2::DocumentInfo::operator =' here (compiling source file D:\FreeCADGit\src\Mod\Import\App\ImportOCAF2.cpp)
2>D:\FreeCADGit\src\Mod\Import\App\ImportOCAF2.h(171,5): message : 'Import::ImportOCAF2::DocumentInfo &Import::ImportOCAF2::DocumentInfo::operator =(const Import::ImportOCAF2::DocumentInfo &)': function was implicitly deleted because 'Import::ImportOCAF2::DocumentInfo' has a data member 'Import::ImportOCAF2::DocumentInfo::children' of reference type (compiling source file D:\FreeCADGit\src\Mod\Import\App\ImportOCAF2.cpp)
2>D:\FreeCADGit\src\Mod\Import\App\ImportOCAF2.h(167): message : see declaration of 'Import::ImportOCAF2::DocumentInfo::children' (compiling source file D:\FreeCADGit\src\Mod\Import\App\ImportOCAF2.cpp)
2>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\include\vector(1314): message : see reference to function template instantiation '_OutIt *std::_Copy_unchecked<_Iter,Import::ImportOCAF2::DocumentInfo*>(_InIt,_InIt,_OutIt)' being compiled
2>        with
2>        [
2>            _OutIt=Import::ImportOCAF2::DocumentInfo *,
2>            _Iter=Import::ImportOCAF2::DocumentInfo *,
2>            _InIt=Import::ImportOCAF2::DocumentInfo *
2>        ] (compiling source file D:\FreeCADGit\src\Mod\Import\App\ImportOCAF2.cpp)
2>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\include\vector(1337): message : see reference to function template instantiation 'void std::vector<Import::ImportOCAF2::DocumentInfo,std::allocator<Import::ImportOCAF2::DocumentInfo>>::_Assign_range<_Iter>(_Iter,_Iter,std::forward_iterator_tag)' being compiled
2>        with
2>        [
2>            _Iter=Import::ImportOCAF2::DocumentInfo *
2>        ] (compiling source file D:\FreeCADGit\src\Mod\Import\App\ImportOCAF2.cpp)
2>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\include\vector(1337): message : see reference to function template instantiation 'void std::vector<Import::ImportOCAF2::DocumentInfo,std::allocator<Import::ImportOCAF2::DocumentInfo>>::_Assign_range<_Iter>(_Iter,_Iter,std::forward_iterator_tag)' being compiled
2>        with
2>        [
2>            _Iter=Import::ImportOCAF2::DocumentInfo *
2>        ] (compiling source file D:\FreeCADGit\src\Mod\Import\App\ImportOCAF2.cpp)
2>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\include\vector(1361): message : see reference to function template instantiation 'void std::vector<Import::ImportOCAF2::DocumentInfo,std::allocator<Import::ImportOCAF2::DocumentInfo>>::assign<Import::ImportOCAF2::DocumentInfo*,0>(_Iter,_Iter)' being compiled
2>        with
2>        [
2>            _Iter=Import::ImportOCAF2::DocumentInfo *
2>        ] (compiling source file D:\FreeCADGit\src\Mod\Import\App\ImportOCAF2.cpp)
2>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\include\vector(1361): message : see reference to function template instantiation 'void std::vector<Import::ImportOCAF2::DocumentInfo,std::allocator<Import::ImportOCAF2::DocumentInfo>>::assign<Import::ImportOCAF2::DocumentInfo*,0>(_Iter,_Iter)' being compiled
2>        with
2>        [
2>            _Iter=Import::ImportOCAF2::DocumentInfo *
2>        ] (compiling source file D:\FreeCADGit\src\Mod\Import\App\ImportOCAF2.cpp)
2>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\include\vector(1345): message : while compiling class template member function 'std::vector<Import::ImportOCAF2::DocumentInfo,std::allocator<Import::ImportOCAF2::DocumentInfo>> &std::vector<Import::ImportOCAF2::DocumentInfo,std::allocator<Import::ImportOCAF2::DocumentInfo>>::operator =(const std::vector<Import::ImportOCAF2::DocumentInfo,std::allocator<Import::ImportOCAF2::DocumentInfo>> &)' (compiling source file D:\FreeCADGit\src\Mod\Import\App\ImportOCAF2.cpp)
2>D:\FreeCADGit\src\Mod\Import\App\ImportOCAF2.h(179): message : see reference to function template instantiation 'std::vector<Import::ImportOCAF2::DocumentInfo,std::allocator<Import::ImportOCAF2::DocumentInfo>> &std::vector<Import::ImportOCAF2::DocumentInfo,std::allocator<Import::ImportOCAF2::DocumentInfo>>::operator =(const std::vector<Import::ImportOCAF2::DocumentInfo,std::allocator<Import::ImportOCAF2::DocumentInfo>> &)' being compiled (compiling source file D:\FreeCADGit\src\Mod\Import\App\ImportOCAF2.cpp)
2>D:\FreeCADGit\src\Mod\Import\App\ImportOCAF2.h(172): message : see reference to class template instantiation 'std::vector<Import::ImportOCAF2::DocumentInfo,std::allocator<Import::ImportOCAF2::DocumentInfo>>' being compiled (compiling source file D:\FreeCADGit\src\Mod\Import\App\ImportOCAF2.cpp)
2>Done building project "Import.vcxproj" -- FAILED.
```

Can you please have a look @realthunder

**Comment by donovaly** [comment]
Here is another warning that should be addressed:

`21>D:\FreeCADGit\src\Mod\Sketcher\Gui\EditModeGeometryCoinManager.cpp(388,33): warning C4305: '=': truncation from 'double' to 'float'`

**Comment by luzpaz** [comment]
Snap build has been [triggered](https://github.com/FreeCAD/FreeCAD-snap/actions/runs/3060448407) and should be available in the ~1.5hours

To test: `snap refresh freecad --channel='latest/edge/toponaming'`  
To switch back to 'edge': `snap refresh freecad --channel='latest/edge'`

**Comment by adrianinsaval** [comment]
@realthunder I found a bug: https://forum.freecadweb.org/viewtopic.php?p=626675#p626675 and another user found another bug in the previous PR too in that thread.
