### PR TITLE
smesh: Fix build failure with vtk 9.4

### LINKED ISSUE #18423: Fails to build against VTK v9.4 (released on 2024-11-22 + has some breaking changes)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Building 1.0.0 with vtk-9.4 fails, with vtk-9.3 it works, looks like [9.4 has some breaking changes](https://docs.vtk.org/en/latest/release_details/9.4.html).

````
 39%] Building CXX object src/3rdParty/salomesmesh/CMakeFiles/SMDS.dir/src/SMDS/SMDS_VolumeOfNodes.cpp.o
/usr/src/t2-src/src.freecad.241210.214008.18573/src/3rdParty/salomesmesh/src/SMDS/SMDS_UnstructuredGrid.cpp: In member function 'void SMDS_UnstructuredGrid::compactGrid(std::vector<int, std::allocator<int> >&, int, std::vector<int, std::allocator<int> >&, int)':
/usr/src/t2-src/src.freecad.241210.214008.18573/src/3rdParty/salomesmesh/src/SMDS/SMDS_UnstructuredGrid.cpp:268:54: error: 'class vtkCellArray' has no member named 'GetValue'
  268 |                int oldFaceLoc = this->FaceLocations->GetValue(i);
      |                                                      ^~~~~~~~
/usr/src/t2-src/src.freecad.241210.214008.18573/src/3rdParty/salomesmesh/src/SMDS/SMDS_UnstructuredGrid.cpp:269:46: error: 'class vtkCellArray' has no member named 'GetValue'
  269 |                int nCellFaces = this->Faces->GetValue(oldFaceLoc++);
      |                                              ^~~~~~~~
/usr/src/t2-src/src.freecad.241210.214008.18573/src/3rdParty/salomesmesh/src/SMDS/SMDS_UnstructuredGrid.cpp:273:50: error: 'class vtkCellArray' has no member named 'GetValue'
  273 |                    int nptsInFace = this->Faces->GetValue(oldFaceLoc++);
      |                                                  ^~~~~~~~
/usr/src/t2-src/src.freecad.241210.214008.18573/src/3rdParty/salomesmesh/src/SMDS/SMDS_UnstructuredGrid.cpp:277:49: error: 'class vtkCellArray' has no member named 'GetValue'
  277 |                        int oldpt = this->Faces->GetValue(oldFaceLoc++);
      |                                                 ^~~~~~~~
/usr/src/t2-src/src.freecad.241210.214008.18573/src/3rdParty/salomesmesh/src/SMDS/SMDS_UnstructuredGrid.cpp:295:19: error: no matching function for call to 'SMDS_UnstructuredGrid::SetCells(vtkUnsignedCharArray*&, vtkIdTypeArray*&, vtkCellArray*&, vtkSmartPointer<vtkCellArray>&, vtkSmartPointer<vtkCellArray>&)'
  295 |     this->SetCells(newTypes, newLocations, newConnectivity, FaceLocations, Faces);
````

### Full version info

```shell
OS: Linux 6.12.1-t2 (xcb)
Architecture: x86_64
Version: 1.0.0.39109 (Git)
Build type: Release
Branch: (HEAD detached at 1.0.0)
Hash: 2fcc5317fe3aee96ca73475986a577719fc78e20
Python 3.12.3, Qt 6.8.1, Coin 4.0.3, Vtk 9.3.1, OCC 7.8.1
Locale: German/Germany (de_DE)
Stylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/
```

### Subproject(s) affected?

None

### Anything else?

Build with vtk-9.3 works fine (shown in about info), with 9.4 not.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by wwmayer**
Fixes #18423

### CODE REVIEW

**Comment by wwmayer** [comment]
@anrub please test this PR with vtk9.4

**Comment by chennes** [comment]
It sounds like this still doesn't quite compile against VTK 9.4, so I'm leaving it so the changes can all be made at once. If you'd prefer to just merge it, @wwmayer, that's also fine with me.

**Comment by StefanBruens** [comment]
1.0.x backport candidate?

**Comment by alerque** [comment]
Yes please on the backport! I'm trying to get the Arch Linux package for freecad building again and it looks like this is the culprit.
