### ISSUE TITLE
Fails to build against VTK v9.4 (released on 2024-11-22 + has some breaking changes)

### ISSUE THREAD

**Issue by anrub** [FreeCAD/FreeCAD#18423]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Building 1.0.0 with vtk-9.4 fails, with vtk-9.3 it works, looks like [9.4 has some breaking changes](https://docs.vtk.org/en/latest/release_details/9.4.html).

````
 39%] Building CXX object src/3rdParty/salomesmesh/CMakeFiles/SMDS.dir/src/SMDS/SMDS_VolumeOfNodes.cpp.o
/usr/src/t2-src/src.freecad.241210.214008.18573/src/3rdParty/salomesmesh/src/SMDS/SMDS_UnstructuredGrid.cpp: In member function 'void SMDS_UnstructuredGrid::compactGrid(std::vector<int, std::allocator<int> >&, int, std::vector<int, std::allocator<int> >&, int)':
/usr/src/t2-src/src.freecad.241210.214008.18573/src/3rdParty/salomesmesh/src/SMDS/SMDS_UnstructuredGrid.cpp:268:54: error: 'class vtkCellArray' has no member named 'GetValue'
  268 |                int oldFaceLoc = this->FaceLocations->GetValue(i);
      |                                                      ^~~~~~~~
/usr/src/t2-src/src.freecad.241210.214008.18573/src/3rdParty/salomesmesh/src/SMDS/SMDS_UnstructuredGrid.cpp:269:46: error: 'class vtkCellArray' has no member named 'GetValue'
  269 |                int nCellFaces = this->Faces->GetValue(oldFaceLoc++);
      |                                              ^~~~~~~~
/usr/src/t2-src/src.freecad.241210.214008.18573/src/3rdParty/salomesmesh/src/SMDS/SMDS_UnstructuredGrid.cpp:273:50: error: 'class vtkCellArray' has no member named 'GetValue'
  273 |                    int nptsInFace = this->Faces->GetValue(oldFaceLoc++);
      |                                                  ^~~~~~~~
/usr/src/t2-src/src.freecad.241210.214008.18573/src/3rdParty/salomesmesh/src/SMDS/SMDS_UnstructuredGrid.cpp:277:49: error: 'class vtkCellArray' has no member named 'GetValue'
  277 |                        int oldpt = this->Faces->GetValue(oldFaceLoc++);
      |                                                 ^~~~~~~~
/usr/src/t2-src/src.freecad.241210.214008.18573/src/3rdParty/salomesmesh/src/SMDS/SMDS_UnstructuredGrid.cpp:295:19: error: no matching function for call to 'SMDS_UnstructuredGrid::SetCells(vtkUnsignedCharArray*&, vtkIdTypeArray*&, vtkCellArray*&, vtkSmartPointer<vtkCellArray>&, vtkSmartPointer<vtkCellArray>&)'
  295 |     this->SetCells(newTypes, newLocations, newConnectivity, FaceLocations, Faces);
````

### Full version info

```shell
OS: Linux 6.12.1-t2 (xcb)
Architecture: x86_64
Version: 1.0.0.39109 (Git)
Build type: Release
Branch: (HEAD detached at 1.0.0)
Hash: 2fcc5317fe3aee96ca73475986a577719fc78e20
Python 3.12.3, Qt 6.8.1, Coin 4.0.3, Vtk 9.3.1, OCC 7.8.1
Locale: German/Germany (de_DE)
Stylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/
```

### Subproject(s) affected?

None

### Anything else?

Build with vtk-9.3 works fine (shown in about info), with 9.4 not.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
cc @wwmayer perhaps you can take a look at this ? (fixing this will help the AUR folks who always live on the bleeding edge)

**Comment by luzpaz** [comment]
> Version: 1.0.0.39109 (Git)

@anrub wondering why your About info isn't showing 1.1-dev.xxxxx  
Have you tested this against HEAD ?

**Comment by anrub** [comment]
> @anrub wondering why your About info isn't showing 1.1-dev.xxxxx Have you tested this against HEAD ?

I tested with main (f3c60) right now, with the same builderror regarding VTK, which makes sense as, [src/3rdParty](https://github.com/FreeCAD/FreeCAD/tree/main/src)
/3rdParty/ hasn't been touched since release.

**Comment by wwmayer** [comment]
Why does the compiler say that "FaceLocations" is of type vtkCellArray? For me it says it's of type vtkIdTypeArray which is a sub-class of vtkAOSDataArrayTemplate.

When looking at the [current status](https://github.com/Kitware/VTK/blob/9a5a236724e01b205425bf3121143aa59c98c950/Common/Core/vtkAOSDataArrayTemplate.h#L78) of this class then the method GetValue still exists.

**Comment by anrub** [comment]
I just did a bisect on VTK between 9.3.0 and 9.4.0 to see at which VTK-commit I can't build FreeCAD anymore. But I can't identify if that could be a local issue?
[vtk_bisect_redo.log](https://github.com/user-attachments/files/18111356/vtk_bisect_redo.log)

First Bad: [`2c2272cb`](https://gitlab.kitware.com/vtk/vtk/-/commit/2c2272cb), Previous [`df8f6819`](https://gitlab.kitware.com/vtk/vtk/-/commit/df8f68196da1825ff237eabdb12641e21a7b1806) works.

**Comment by StefanBruens** [comment]
> Why does the compiler say that "FaceLocations" is of type vtkCellArray? For me it says it's of type vtkIdTypeArray which is a sub-class of vtkAOSDataArrayTemplate.
> 
> When looking at the [current status](https://github.com/Kitware/VTK/blob/9a5a236724e01b205425bf3121143aa59c98c950/Common/Core/vtkAOSDataArrayTemplate.h#L78) of this class then the method GetValue still exists.

`vtkUnstructuredGrid::FaceLocations` is no longer a `vtkIdTypeArray`, but `vtkUnstructuredGrid::LegacyFaceLocations`. See

https://github.com/Kitware/VTK/commit/13b346ad16e457f5c84f3092049059cfd947e7a7

**Comment by wwmayer** [comment]
Thanks for the link.

Here is a PR that is supposed to fix the build failure: https://github.com/FreeCAD/FreeCAD/pull/18543

According to the comments in the vtk sources using LegacyFaces and LegacyFaceLocations is not the most efficient way any more because calling GetFaces() / GetFaceLocations() will perform some extra copying in vtk >= 9.4.

**Comment by maxwxyz** [comment]
@anrub could you test if the PR fixes your issue?

**Comment by anrub** [comment]
I cherry-picked the commit ontop of [main](https://github.com/anrub/FreeCAD) and built it against VTK 9.4.0, and get the error, but unrelated to the change, it also occurs on main with VTK-9.4.0
` SMDS_UnstructuredGrid.cpp:1032:25: error: no matching function for call to 'vtkCellLinks::BuildLinks(SMDS_UnstructuredGrid*)''` 

Line 3797 in the full build log [freecad.log.txt](https://github.com/user-attachments/files/18210411/freecad.log.txt)

```
/usr/src/t2-src/src.freecad.241220.123528.21095/FreeCAD.git/src/3rdParty/salomesmesh/src/SMDS/SMDS_UnstructuredGrid.cpp: In member function 'void SMDS_UnstructuredGrid::BuildLinks()':
/usr/src/t2-src/src.freecad.241220.123528.21095/FreeCAD.git/src/3rdParty/salomesmesh/src/SMDS/SMDS_UnstructuredGrid.cpp:1032:25: error: no matching function for call to 'vtkCellLinks::BuildLinks(SMDS_UnstructuredGrid*)'
 1032 |   GetLinks()->BuildLinks(this);
      |   ~~~~~~~~~~~~~~~~~~~~~~^~~~~~
In file included from /usr/src/t2-src/src.freecad.241220.123528.21095/FreeCAD.git/src/3rdParty/salomesmesh/inc/SMDS_UnstructuredGrid.hxx:30:
/usr/include/vtk-9.4/vtkCellLinks.h:64:8: note: candidate: 'virtual void vtkCellLinks::BuildLinks()'
   64 |   void BuildLinks() override;
      |        ^~~~~~~~~~
/usr/include/vtk-9.4/vtkCellLinks.h:64:8: note:   candidate expects 0 arguments, 1 provided
[ 40%] Building CXX object src/3rdParty/salomesmesh/CMakeFiles/SMDS.dir/src/SMDS/SMDS_VertexPosition.cpp.o
make[2]: *** [src/3rdParty/salomesmesh/CMakeFiles/SMDS.dir/build.make:474: src/3rdParty/salomesmesh/CMakeFiles/SMDS.dir/src/SMDS/SMDS_UnstructuredGrid.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```

**Comment by wwmayer** [comment]
This is strange. If you look at the code then the call of `BuildLinks(this)` is explicitly called for < vtk 9.3.0
```
  this->Links = SMDS_CellLinks::New();
  GetLinks()->Allocate(this->GetNumberOfPoints());
  GetLinks()->Register(this);
//FIXME: vtk9
  #if VTK_VERSION_NUMBER < VTK_VERSION_CHECK(9,3,0)
  GetLinks()->BuildLinks(this);
  #else
  GetLinks()->SetDataSet(this);
  GetLinks()->BuildLinks();
  #endif
  GetLinks()->Delete();
```
What I can imagine is that the macro is not defined. Does it fix the failure if you include `#include <vtkVersionMacros.h>`?

**Comment by anrub** [comment]
@wwmayer Yes, it works with the header, thank you so much!

**Comment by wwmayer** [comment]
OK, I will update my PR, then. Thanks for your feedback!
