### PR TITLE
FEM: Data extraction and visualization

### PR DESCRIPTION
**Pull request by ickby**
This PR adds functionality to FEM post processing to extract data from filters, and to visualize it in plots and tables. Much work was done to create a sound basic framework, that is easily extensible with more visualization types in the future. 

- New objects are added for data visualization - Lineplot, Histogram, Table
  - corresponding data extraction objects are added which extract data from filters for the relevant visualization
  - it is integrated well with the new multiframe code, allowing data visualization over all frames in a result
- It adds a data extraction task panel to each filter
  -  allowing to view a data summary and the full dataset as table
  - enabling the user to add any data of the filter to any visualization type
- Everything is setup to allow other modules to register their own data extractions and visualizations, so that the UI and workflow can be easily extended for custom needs

Forum discussion: https://forum.freecad.org/viewtopic.php?t=95732

image

The implementation is done in python, with a few bridges required to use it from the c++ implemented filters. It relies on the new vtk python integration, and therefore is only available if FreeCAD is build with this integration available. If not available the functionality is omitted, but FreeCAD builds and works without issue, aslo Test are passing. 

This development process included much experimentation and testing. I tried to clean up as much as possible, but maybe 
overlooked stuff. Code review welcome.

Also usability and workflow testing is appreciated.
@marioalexis84, @FEA-eng, @maxwxyz

### CODE REVIEW

**Comment by maxwxyz** [comment]
@FreeCAD/design-working-group FYI

File: src/Mod/Fem/Gui/TaskPostExtraction.cpp [hunk 1]
```diff
@@ -0,0 +1,182 @@
...
+
+                    auto layout = new QVBoxLayout();
+                    layout->addWidget(widget);
+                    setLayout(layout);
+                    return;
+                }
+            }
+        }
+    }
+    // if we are here somethign went wrong!
```
Comment (luzpaz) [inline src/Mod/Fem/Gui/TaskPostExtraction.cpp:95]: `something`

**Review by luzpaz — CHANGES_REQUESTED** [review]

**Comment by luzpaz** [comment]
@ickby this is such a great submission.  
Question: some of the dialog windows that open (as seen in the YT clip you shared) don't actually have a title. Instead they are labeled 'FreeCAD", is that intended ? See for instance below:  

Screenshot_20250510_105204
Screenshot_20250510_105312
Screenshot_20250510_105407

File: src/Mod/Fem/Gui/TaskPostExtraction.cpp (hunk 1 above)
Comment (ickby) [reply src/Mod/Fem/Gui/TaskPostExtraction.cpp]: corrected

**Comment by ickby** [comment]
> Question: some of the dialog windows that open (as seen in the YT clip you shared) don't actually have a title. Instead they are labeled 'FreeCAD", is that intended ? See for instance below:

Ah that was an oversight, I did not set the title for the dialogs. Corrected with the last update.

**Comment by FEA-eng** [comment]
I get the following errors when double-clicking on the results pipeline:

```
20:33:38  pyException: Traceback (most recent call last):
  File "/home/ubuntu/Documents/freecad_fem_extract/freecad-source/build/Mod/Fem/femguiutils/data_extraction.py", line 82, in __init__
    self.onPostDataChanged(self.Object)
  File "/home/ubuntu/Documents/freecad_fem_extract/freecad-source/build/Mod/Fem/femguiutils/data_extraction.py", line 140, in onPostDataChanged
    table.InsertColumn(points, 0)
<class 'AttributeError'>: 'vtkmodules.vtkCommonDataModel.vtkTable' object has no attribute 'InsertColumn'
20:33:38  <Gui> Document.cpp(583): Unable to import data extraction widget
```

**Comment by ickby** [comment]
> InsertColumn

You are running VTK9.1, right?  I would assume InsertColumn was introduced later... man that is the worst part of VTK documentation, there is no way to see what is new and what not, and when stuff was introduced... I try to replace it.

**Comment by ickby** [comment]
@FEA-eng I removed the critical function and pushed the update. It could very well be that there are more that are not supported by VTK9.1, I have not yet a way to test this.  So please keep the tests running :)

**Comment by FEA-eng** [comment]
@ickby Now the pipeline opens but there are still some error messages:

```
13:01:03  pyException: Traceback (most recent call last):
  File "/home/ubuntu/Documents/freecad_fem_extract/freecad-source/build/Mod/Fem/femguiutils/data_extraction.py", line 85, in __init__
    self._extraction_view = ExtractLinkView(self.Object, True, self)
  File "/home/ubuntu/Documents/freecad_fem_extract/freecad-source/build/Mod/Fem/femguiutils/extract_link_view.py", line 499, in __init__
    self._add = _TreeChoiceButton(build_add_to_visualization_tree_model())
  File "/home/ubuntu/Documents/freecad_fem_extract/freecad-source/build/Mod/Fem/femguiutils/extract_link_view.py", line 179, in __init__
    self.tree_view.setEditTriggers(QtGui.QTreeView.EditTriggers.NoEditTriggers)
<class 'AttributeError'>: type object 'PySide2.QtWidgets.QAbstractItemView.EditTriggers' has no attribute 'NoEditTriggers'
13:01:03  Unable to import data extraction widget
```
```
OS: Ubuntu 22.04.5 LTS (ubuntu:GNOME/ubuntu/wayland)
Architecture: x86_64
Version: 1.1.0dev.41652 (Git)
Build date: 2025/05/11 19:00:55
Build type: Unknown
Branch: FEM_extract_data
Hash: 5672b85d8e83784c73054aaea97bac8433dfa13e
Python 3.10.12, Qt 5.15.3, Coin 4.0.0, Vtk 9.1.0, boost 1_74, Eigen3 3.4.0, PySide 5.15.2
shiboken 5.15.2, SMESH 7.7.1.0, xerces-c 3.2.3, OCC 7.5.1
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Logical DPI/Physical DPI/Pixel Ratio: 96/95.9552/1
```

**Comment by ickby** [comment]
Ok, I set up a virtual machine and tested everything with Ubuntu 24.05. Found some version problems with VTK, PySide and Matplotlib. But that should all work now. 

Ready for the next run of tests :)

**Comment by luzpaz** [comment]
Definitely not qualified to review :blush:

**Comment by ickby** [comment]
> Definitely not qualified to review 😊
I think your initial mark of the spelling error is showing as "change requested" and "merging is blocked". I thought you have to somehow approve the changes for this to go away. But not sure tbh.

**Review by luzpaz — APPROVED** [review]

**Comment by luzpaz** [comment]
ITC, FWIW, I approve :laughing:

**Comment by MisterMakerNL** [comment]
This looks really great for users that need this, one step closer to more professional users!!
Hopefully I get some time to explore all this in the future!

**Comment by marioalexis84** [comment]
If you wait until the weekend, I can do a review.

**Comment by FEA-eng** [comment]
I tested it and it looks good (I haven't found any issues) but what's the meaning of "index"? Is that just a node number? Why is it limited to 99 when creating a table with index over frames but not when creating a line plot?

**Comment by ickby** [comment]
Yes index is node number. Do you think renaming makes the purpose more clear? It appears in 3 locations:
1. Index field for plots and tables
2. Index over frame name
3. Index property for the node to use

It should be the same name for all. 

Ah the 99 limitations is just a oversight of me in the UI file. I will correct that.

**Comment by FEA-eng** [comment]
> Yes index is node number. Do you think renaming makes the purpose more clear? It appears in 3 locations:

If it's always the node number (not e.g. element number depending on the case) then it indeed would be good to rename it. Unless such a change would be problematic, then we should just clarify that it's node number in the documentation and possible in the tooltips.

> Ah the 99 limitations is just a oversight of me in the UI file. I will correct that.

Great. One more strange thing I've noticed is that, regardless of what I enter as index, when creating a line plot or a table with IndexOverFrames there are no results (even for position). It keeps saying "Not sufficient frames available in data, cannot extract data". Is it because analyses with a single frame are treated as having no frames (#20937)?

image

**Comment by FEA-eng** [comment]
> For the behavior: yes, right now it expects at least two frames. Would you expect to also extract the data for single or no frame, getting the 1 result out? The current way was driven by line plots, but now thinking about it it could also display just a point in the line plots.

Yes, I think it should work for analyses with just one frame (currently treated as no frames). They are the most common ones and other postprocessors also handle it this way - show just a single value and point in line plots.

File: src/Mod/Fem/Gui/TaskPostBoxes.cpp [hunk 2]
```diff
@@ -393,6 +408,22 @@ void TaskDlgPost::modifyStandardButtons(QDialogButtonBox* box)
...
+            // get the task widget and check if it is a post widget
+            auto widget = task_box->groupLayout()->itemAt(0)->widget();
+            if (auto post_widget = dynamic_cast<TaskPostWidget*>(widget)) {
+                if (post_widget->initiallyCollapsed()) {
+                    post_widget->setGeometry(QRect(QPoint(0, 0), post_widget->sizeHint()));
+                    task_box->hideGroupBox();
+                }
+            }
+        }
+    }
```
Comment (hyarion) [inline src/Mod/Fem/Gui/TaskPostBoxes.cpp]: There are a few things I note here:
* deep nesting https://freecad.github.io/DevelopersHandbook/bestpractices/c++practices.html#main-code-path-and-indentation
* `dynamic_cast` instead of `freecad_cast` see PR 20518 and 20694
* using `auto` without `*` for pointers - while not a problem it can be nice for consistency (people often get it wrong when `const` is added as `const auto` != `const auto*` )

Another way of writing this could be:
```suggestion
    for (auto& widget : Content) {
        auto* task_box = freecad_cast<Gui::TaskView::TaskBox*>(widget)
        if (!task_box) {
            continue;

        // get the task widget and check if it is a post widget
        auto* widget = task_box->groupLayout()->itemAt(0)->widget();
        auto* post_widget = freecad_cast<TaskPostWidget*>(widget);
        if (!post_widget || !post_widget->initiallyCollapsed()) {
            continue;
        }

        post_widget->setGeometry(QRect(QPoint(0, 0), post_widget->sizeHint()));
        task_box->hideGroupBox();
    }
```

Not a showstopper, just an FYI or discussion starter :)

File: src/Mod/Fem/Gui/TaskPostExtraction.cpp [hunk 3]
```diff
@@ -0,0 +1,185 @@
...
+                QWidget* widget = qobject_cast<QWidget*>(object);
+                if (widget) {
+                    // finally we have the usable QWidget. Add to us!
+
+                    auto layout = new QVBoxLayout();
+                    layout->addWidget(widget);
+                    setLayout(layout);
+                    return;
+                }
+            }
```
Comment (hyarion) [inline src/Mod/Fem/Gui/TaskPostExtraction.cpp]: [`qobject_cast` can be used on `nullptr`s without any issues](https://doc.qt.io/qt-6/qobject.html#qobject_cast):
> `template <typename T> T qobject_cast(const [QObject](https://doc.qt.io/qt-6/qobject.html#QObject) *object)`
> If object is `nullptr` then it will also return `nullptr`

```suggestion
            if (auto* widget = qobject_cast<QWidget*>(wrap.toQObject(pywidget))) {
                // finally we have the usable QWidget. Add to us!

                auto* layout = new QVBoxLayout();
                layout->addWidget(widget);
                setLayout(layout);
                return;
            }
```

File: src/Mod/Fem/femcommands/manager.py [hunk 4]
```diff
@@ -380,7 +379,9 @@ def add_filter_set_edit(self, filtertype):
         # like add_obj_on_gui_selobj_noset_edit but the selection is kept
         # and the selobj is expanded in the tree to see the added obj
 
-        # check if we should use python filter
+        # check if we should use python fitler
```
Comment (hyarion) [inline src/Mod/Fem/femcommands/manager.py]: I don't understand this change, what's a fitler?

File: src/Mod/Fem/Gui/ViewProviderFemPostObject.cpp [hunk 5]
```diff
@@ -1019,8 +1023,13 @@ bool ViewProviderFemPostObject::setEdit(int ModNum)
 void ViewProviderFemPostObject::setupTaskDialog(TaskDlgPost* dlg)
 {
     assert(dlg->getView() == this);
-    auto panel = new TaskPostDisplay(this);
-    dlg->addTaskBox(panel->windowIcon().pixmap(32), panel);
+    auto disp_panel = new TaskPostDisplay(this);
```
Comment (kadet1090) [inline src/Mod/Fem/Gui/ViewProviderFemPostObject.cpp]: One thing is FreeCAD mostly uses `camelCase` for local variables - I think that it is quite important to keep that consistent across codebase.

**Comment by luzpaz** [comment]
@ickby thanks for all the work so far, any chance you can respond to the above feedback ?

**Comment by ickby** [comment]
I will, just have been on holiday. Hope to get it rolling again next week.

File: src/Mod/Fem/Gui/TaskPostBoxes.cpp (hunk 2 above)
Comment (ickby) [reply src/Mod/Fem/Gui/TaskPostBoxes.cpp]: I changed the nesting and auto usage as proposed. 
freecad_cast is not applicable here, as the objects to be cast are QWidgets, which are not FreeCAD objects. Therefore one needs to use dynamic_cast as far as I know.

File: src/Mod/Fem/Gui/TaskPostExtraction.cpp (hunk 3 above)
Comment (ickby) [reply src/Mod/Fem/Gui/TaskPostExtraction.cpp]: ah good to know! changed it.

File: src/Mod/Fem/femcommands/manager.py (hunk 4 above)
Comment (ickby) [reply src/Mod/Fem/femcommands/manager.py]: neither do I :)  Most likely happened during refactoring somehow, will change it back.

File: src/Mod/Fem/Gui/ViewProviderFemPostObject.cpp (hunk 5 above)
Comment (ickby) [reply src/Mod/Fem/Gui/ViewProviderFemPostObject.cpp]: I agree.

**Comment by ickby** [comment]
Incorporated the changes and rebased on latest main branch

File: src/Mod/Fem/Gui/TaskPostBoxes.cpp (hunk 2 above)
Comment (kadet1090) [reply src/Mod/Fem/Gui/TaskPostBoxes.cpp]: `qobject_cast` would be a better fit if they are `QObject`s

File: src/Mod/Fem/femguiutils/post_visualization.py [hunk 6]
```diff
@@ -0,0 +1,179 @@
...
+
+import copy
+from dataclasses import dataclass
+
+from PySide import QtCore
+
+import FreeCAD
+
+
+# Registry to handle visulization commands
```
Comment (luzpaz) [inline src/Mod/Fem/femguiutils/post_visualization.py]: visulization ==> visualization

Comment (luzpaz) [reply src/Mod/Fem/femguiutils/post_visualization.py]: There are more typos as well per the CI:  

```
src/Mod/Fem/femobjects/base_fempostextractors.py:24: objcts ==> objects
src/Mod/Fem/femobjects/base_fempostextractors.py:130: representive ==> representative
src/Mod/Fem/femobjects/base_fempostextractors.py:262: representive ==> representative
src/Mod/Fem/femobjects/base_fempostextractors.py:390: representive ==> representative
src/Mod/Fem/femtaskpanels/base_fempostpanel.py:45: mimicing ==> mimicking
src/Mod/Fem/femviewprovider/view_base_femobject.py:47: verison ==> version
src/Mod/Fem/femviewprovider/view_base_fempostextractors.py:70: happend ==> happened, happens, happen
src/Mod/Fem/femviewprovider/view_base_fempostvisualization.py:128: proeprty ==> property
src/Mod/Fem/femviewprovider/view_post_histogram.py:91: wierd ==> weird
src/Mod/Fem/femviewprovider/view_post_histogram.py:230: wierd ==> weird
src/Mod/Fem/femviewprovider/view_post_histogram.py:252: specialy ==> specially
src/Mod/Fem/femviewprovider/view_post_histogram.py:398: shoud ==> should
src/Mod/Fem/femviewprovider/view_post_histogram.py:398: rigth ==> right
src/Mod/Fem/femviewprovider/view_post_lineplot.py:90: wierd ==> weird
src/Mod/Fem/femviewprovider/view_post_lineplot.py:245: wierd ==> weird
src/Mod/Fem/femviewprovider/view_post_lineplot.py:269: specialy ==> specially
src/Mod/Fem/femviewprovider/view_post_lineplot.py:406: shoud ==> should
src/Mod/Fem/femviewprovider/view_post_lineplot.py:406: rigth ==> right
src/Mod/Fem/femviewprovider/view_post_table.py:157: wierd ==> weird
src/Mod/Fem/femviewprovider/view_post_table.py:179: specialy ==> specially
```

**Comment by ickby** [comment]
Typo corrected and CodeQL handled (CodeQL errors have been false positives, nonetheless I updated so that warnings and infos should be resolved)

**Comment by luzpaz** [comment]
@ickby there were more typos mentioned but I can make a follow-up PR to fix them so don't worry about it. I'd rather it not block this PR from being merged.

**Review by luzpaz — APPROVED** [review]

**Comment by hyarion** [comment]
@ickby there's a bunch of lint warnings. Is this something you would like to fix? otherwise I can do it.

**Comment by luzpaz** [comment]
@hyarion https://github.com/FreeCAD/FreeCAD/pull/21221#issuecomment-2974767637 (if you're just referring to the spelling typos)

**Comment by ickby** [comment]
I pushed a commit with some lint updates. Not all are correctable as they are miss-interpreted from the linter, and I do not know how to mark them in the code to be ignored.

File: src/Mod/Fem/femviewprovider/view_post_table.py [hunk 7]
```diff
@@ -0,0 +1,297 @@
...
+import Plot
+import FemGui
+from PySide import QtGui, QtCore
+from PySide.QtCore import QT_TRANSLATE_NOOP
+
+import io
+import numpy as np
+import matplotlib as mpl
+
+from vtkmodules.numpy_interface.dataset_adapter import VTKArray
```
[the remark this answers is not in the document]
Comment (ickby) [reply src/Mod/Fem/femviewprovider/view_post_table.py]: fixed

File: src/Mod/Fem/femviewprovider/view_post_table.py [hunk 8]
```diff
@@ -0,0 +1,297 @@
...
+import FreeCADGui
+
+import Plot
+import FemGui
+from PySide import QtGui, QtCore
+from PySide.QtCore import QT_TRANSLATE_NOOP
+
+import io
+import numpy as np
+import matplotlib as mpl
```
[the remark this answers is not in the document]
Comment (ickby) [reply src/Mod/Fem/femviewprovider/view_post_table.py]: fixed

File: src/Mod/Fem/femviewprovider/view_post_table.py [hunk 9]
```diff
@@ -0,0 +1,297 @@
...
+import FreeCAD
+import FreeCADGui
+
+import Plot
+import FemGui
+from PySide import QtGui, QtCore
+from PySide.QtCore import QT_TRANSLATE_NOOP
+
+import io
+import numpy as np
```
[the remark this answers is not in the document]
Comment (ickby) [reply src/Mod/Fem/femviewprovider/view_post_table.py]: fixed

File: src/Mod/Fem/femviewprovider/view_post_table.py [hunk 10]
```diff
@@ -0,0 +1,297 @@
...
+
+import FreeCAD
+import FreeCADGui
+
+import Plot
+import FemGui
+from PySide import QtGui, QtCore
+from PySide.QtCore import QT_TRANSLATE_NOOP
+
+import io
```
[the remark this answers is not in the document]
Comment (ickby) [reply src/Mod/Fem/femviewprovider/view_post_table.py]: fixed

File: src/Mod/Fem/femviewprovider/view_post_table.py [hunk 11]
```diff
@@ -0,0 +1,297 @@
...
+
+## @package view_post_table
+#  \ingroup FEM
+#  \brief view provider for post table object
+
+import FreeCAD
+import FreeCADGui
+
+import Plot
+import FemGui
```
[the remark this answers is not in the document]
Comment (ickby) [reply src/Mod/Fem/femviewprovider/view_post_table.py]: fixed

File: src/Mod/Fem/femviewprovider/view_post_table.py [hunk 12]
```diff
@@ -0,0 +1,297 @@
...
+__url__ = "https://www.freecad.org"
+
+## @package view_post_table
+#  \ingroup FEM
+#  \brief view provider for post table object
+
+import FreeCAD
+import FreeCADGui
+
+import Plot
```
[the remark this answers is not in the document]
Comment (ickby) [reply src/Mod/Fem/femviewprovider/view_post_table.py]: fixed

File: src/Mod/Fem/femviewprovider/view_post_lineplot.py [hunk 13]
```diff
@@ -0,0 +1,583 @@
...
+import io
+import numpy as np
+import matplotlib as mpl
+
+from vtkmodules.numpy_interface.dataset_adapter import VTKArray
+
+from . import view_base_fempostextractors
+from . import view_base_fempostvisualization
+from femtaskpanels import task_post_lineplot
+from femguiutils import post_visualization as pv
```
[the remark this answers is not in the document]
Comment (ickby) [reply src/Mod/Fem/femviewprovider/view_post_lineplot.py]: fixed

File: src/Mod/Fem/femviewprovider/view_post_lineplot.py [hunk 14]
```diff
@@ -0,0 +1,583 @@
...
+
+## @package view_post_lineplot
+#  \ingroup FEM
+#  \brief view provider for post line plot object
+
+import FreeCAD
+import FreeCADGui
+
+import Plot
+import FemGui
```
[the remark this answers is not in the document]
Comment (ickby) [reply src/Mod/Fem/femviewprovider/view_post_lineplot.py]: fixed

File: src/Mod/Fem/femviewprovider/view_post_histogram.py [hunk 15]
```diff
@@ -0,0 +1,602 @@
...
+
+## @package view_post_lineplot
+#  \ingroup FEM
+#  \brief view provider for post line plot object
+
+import FreeCAD
+import FreeCADGui
+
+import Plot
+import FemGui
```
[the remark this answers is not in the document]
Comment (ickby) [reply src/Mod/Fem/femviewprovider/view_post_histogram.py]: fixed

File: src/Mod/Fem/femviewprovider/view_base_fempostvisualization.py [hunk 16]
```diff
@@ -0,0 +1,131 @@
...
+
+from PySide import QtGui, QtCore
+
+import Plot
+import FreeCAD
+import FreeCADGui
+
+from . import view_base_femobject
+
+_GuiPropHelper = view_base_femobject._GuiPropHelper
```
[the remark this answers is not in the document]
Comment (ickby) [reply src/Mod/Fem/femviewprovider/view_base_fempostvisualization.py]: fixed

File: src/Mod/Fem/femviewprovider/view_base_fempostvisualization.py [hunk 17]
```diff
@@ -0,0 +1,131 @@
...
+__author__ = "Stefan Tröger"
+__url__ = "https://www.freecad.org"
+
+## @package view_base_fempostvisualizations
+#  \ingroup FEM
+#  \brief view provider for post visualization object
+
+from PySide import QtGui, QtCore
+
+import Plot
```
[the remark this answers is not in the document]
Comment (ickby) [reply src/Mod/Fem/femviewprovider/view_base_fempostvisualization.py]: fixed

File: src/Mod/Fem/femviewprovider/view_base_fempostextractors.py [hunk 18]
```diff
@@ -0,0 +1,149 @@
...
+#  \ingroup FEM
+#  \brief view provider for post line plot object
+
+import FreeCAD
+import FreeCADGui
+
+from PySide import QtGui
+
+import femobjects.base_fempostextractors as fpe
+from femtaskpanels import task_post_extractor
```
[the remark this answers is not in the document]
Comment (ickby) [reply src/Mod/Fem/femviewprovider/view_base_fempostextractors.py:37]: fixed

File: src/Mod/Fem/femcommands/commands.py [hunk 19]
```diff
@@ -1289,3 +1289,12 @@
 
 if "BUILD_FEM_VTK_PYTHON" in FreeCAD.__cmake__:
     FreeCADGui.addCommand("FEM_PostFilterGlyph", _PostFilterGlyph())
+
+    # setup all visualization commands (register by importing)
```
[the remark this answers is not in the document]
Comment (ickby) [reply src/Mod/Fem/femcommands/commands.py:1293]: Falls positive. The import needs to be there for the side effects of it registering the types.

File: src/Mod/Fem/femcommands/commands.py [hunk 20]
```diff
@@ -1289,3 +1289,12 @@
...
+    import femobjects.post_lineplot
```
[the remark this answers is not in the document]
Comment (ickby) [reply src/Mod/Fem/femcommands/commands.py:1294]: Falls positive. The import needs to be there for the side effects of it registering the types.

File: src/Mod/Fem/femcommands/commands.py [hunk 21]
```diff
@@ -1289,3 +1289,12 @@
...
+    import femobjects.post_histogram
+    import femobjects.post_table
```
[the remark this answers is not in the document]
Comment (ickby) [reply src/Mod/Fem/femcommands/commands.py:1296]: Falls positive. The import needs to be there for the side effects of it registering the types.

File: src/Mod/Fem/femobjects/base_fempostextractors.py [hunk 22]
```diff
@@ -0,0 +1,398 @@
...
+        if prop == "Source":
+            # check if the source is a Post object
+            if obj.Source and not obj.Source.isDerivedFrom("Fem::FemPostObject"):
+                FreeCAD.Console.PrintWarning("Invalid object: Line source must be FemPostObject")
+                obj.Source = None
+
+    def get_vtk_table(self, obj):
+        if not obj.DataTable:
+            obj.DataTable = vtkTable()
+
```
[the remark this answers is not in the document]
Comment (ickby) [reply src/Mod/Fem/femobjects/base_fempostextractors.py:114]: Not sure what the linter means here. All code returns are well defined.

[the remark this answers is not in the document]
Comment (hyarion) [reply src/Mod/Fem/femobjects/base_fempostextractors.py:114]: Strange...

**Review by hyarion — APPROVED** [review]

**Comment by luzpaz** [comment]
Typo fixes in #22149

**Comment by negril** [comment]
The check in https://github.com/FreeCAD/FreeCAD/pull/21221/commits/8cec9ad7f92f3c38d48af55ab67b60876233ecd3 checks for `vtkVersion.GetVTKMajorVersion() > 9`, so would require vtk-10.4 to be taken.

To add, the check should be for `major > 9 ||major == 9 && minor > 3`, otherwise e.g. 10.0 would not match either.

**Comment by ickby** [comment]
> To add, the check should be for `major > 9 ||major == 9 && minor > 3`, otherwise e.g. 10.0 would not match either.

good catch. Did you experience any problems with that, or just noticed?

**Comment by negril** [comment]
> Did you experience any problems with that, or just noticed?

It doesn't work with vtk-9.5.0. So the tests already fail.

```
======================================================================
ERROR: test_pyimport_all_FEM_modules (femtest.app.test_common.TestFemCommon.test_pyimport_all_FEM_modules)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.13/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/usr/lib/python3.13/unittest/case.py", line 651, in run
    self._callTestMethod(testMethod)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/lib/python3.13/unittest/case.py", line 606, in _callTestMethod
    if method() is not None:
       ~~~~~~^^
  File "/var/tmp/paludis/media-gfx-freecad-9999/work/freecad-9999_build/Mod/Fem/femtest/app/test_common.py", line 133, in test_pyimport_all_FEM_modules
    __import__(f"{mod}")
    ~~~~~~~~~~^^^^^^^^^^
  File "/var/tmp/paludis/media-gfx-freecad-9999/work/freecad-9999_build/Mod/Fem/femguiutils/data_extraction.py", line 43, in <module>
    from vtkmodules.vtkInfovisCore import vtkDataObjectToTable
ImportError: cannot import name 'vtkDataObjectToTable' from 'vtkmodules.vtkInfovisCore' (/usr/lib/python3.13/site-packages/vtkmodules/vtkInfovisCore.cpython-313-x86_64-linux-gnu.so)
```
