### ISSUE TITLE
CAM:  Custom post processors fail in v1.2

### ISSUE THREAD

**Issue by Connor9220** [FreeCAD/FreeCAD#26006]
### Workbench affected?

None

### Problem description

Custom post processors no longer work with v1.2

I get the following error

```
Running the Python command 'CAM_Post' failed:
Traceback (most recent call last):
  File "/home/billy/workspace/freecad/freecad-main/build/debug/Mod/CAM/Path/Post/Command.py", line 218, in Activated
    post_data = postprocessor.export()
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/billy/workspace/freecad/freecad-main/build/debug/Mod/CAM/Path/Post/Processor.py", line 522, in export
    gcode = self.script_module.export(sublist, "-", self._job.PostProcessorArgs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/billy/.local/share/FreeCAD/Macro/NibblerBOT_post.py", line 471, in export
    dia.editor.setText(gcode)
    ^^^^^^^^^^^^^^^^^^

'CodeEditor' object has no attribute 'setText'
```

### Steps to reproduce

Using v1.2 run any v1.1 post processor (you'll need to copy a v1.1 from the scripts directory and place it in your Macro directory, rename it so you can easily identify it.) 

Try posting a CAM job using that post processor.

### Expected behavior

Should open up the dialog and continue to post.

### Actual behavior

Get this error

```
Running the Python command 'CAM_Post' failed:
Traceback (most recent call last):
  File "/home/billy/workspace/freecad/freecad-main/build/debug/Mod/CAM/Path/Post/Command.py", line 218, in Activated
    post_data = postprocessor.export()
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/billy/workspace/freecad/freecad-main/build/debug/Mod/CAM/Path/Post/Processor.py", line 522, in export
    gcode = self.script_module.export(sublist, "-", self._job.PostProcessorArgs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/billy/.local/share/FreeCAD/Macro/NibblerBOT_post.py", line 471, in export
    dia.editor.setText(gcode)
    ^^^^^^^^^^^^^^^^^^

'CodeEditor' object has no attribute 'setText'
```

### Development version About Info (in Safe Mode)

```shell
OS: Debian GNU/Linux 12 (bookworm) (GNOME/gnome/xcb)
Architecture: x86_64
Version: 1.2.0dev.44573 +1 (Git)
Build date: 2025/12/03 20:22:43
Build type: Unknown
Branch: AddMachineEditor
Hash: 0b94d21343b0ea0bdcf7a8883716ec45cb9ff34f
Python 3.11.13, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: English/United States (en_US)
Navigation Style/Orbit Style/Rotation Mode: Gesture/Turntable/Object center
Stylesheet/Theme/QtStyle: OpenDark.qss/OpenDark/
Logical DPI/Physical DPI/Pixel Ratio: 96/90.0633/1
Installed mods: 
  * OpenTheme 2025.5.20
```

### Last known good version (optional)

```shell
Before PR #23862 was merged in.
```

**Comment by tarman3** [comment]
- #26008
