### ISSUE TITLE
Compilation error caused by ShapeFix_Solid in OCC

### ISSUE THREAD

**Issue by FEA-eng** [FreeCAD/FreeCAD#26875]
### Problem description

Currently, I cannot compile the main branch using CMake on Ubuntu 22.04.5 LTS. Compilation log (attached) points to some OCC functions such as ShapeFix_Solid. As pointed out by @Syres916 [here](https://forum.freecad.org/viewtopic.php?t=102467#p867216), it's most likely due to the following commit: https://github.com/FreeCAD/FreeCAD/commit/5fbd150b18d01c16f86062b6a2e26e31ed4650b3

Apparently, OCCT 7.6.3 is enough to compile, but I assume it's not a planned change in the required OCCT version.

[info.txt](https://github.com/user-attachments/files/24567247/info.txt)

### Workbench affected?

Core (App, Gui,...)

### Steps to reproduce

Compile with OCCT older than 7.6.3

### Expected behavior

Compilation runs to completion

### Actual behavior

Compilation fails with:

```
[ 73%] Built target FreeCADGui
make: *** [Makefile:146: all] Error 2
```

### Development version About Info (in Safe Mode)

From the newest AppImage build:
```
OS: Ubuntu 22.04.5 LTS (ubuntu:GNOME/ubuntu/wayland)
Architecture: x86_64
Version: 1.2.0dev.20260106 (Git shallow)
Build date: 2026/01/06 15:36:19
Build type: Release
Branch: (HEAD detached at 9b64da8)
Hash: 9b64da827a112d88a025be26316e3d023ff491dc
Python 3.11.14, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: English/United States (en_US)
Navigation Style/Orbit Style/Rotation Mode: Touchpad/Rounded Arcball/Window center
Stylesheet/Theme/QtStyle: FreeCAD.qss/FreeCAD Light/
Logical DPI/Physical DPI/Pixel Ratio: 96/95.9552/1
```

### Last known good version (optional)

```shell

```

**Comment by maxwxyz** [comment]
On the upcoming developer meetings there is a topic to drop 22.04 support.

**Comment by FEA-eng** [comment]
> On the upcoming developer meetings there is a topic to drop 22.04 support.

Yeah, I've seen the announcement that it's already planned for April.

**Comment by ipatch** [comment]
does it make sense to update the cmake files to let the user know that occt <= 7.6.3 is no longer supported?

**Comment by FEA-eng** [comment]
I switched to Pixi compilation on Windows, but I assume the issue is still relevant.
