### ISSUE TITLE
Problem when AxialMove is used in Assembly3 in the latest development versions of FreeCad.

### ISSUE THREAD

**Issue by jpg87Fr** [FreeCAD/FreeCAD#22037]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Problem description

Hello, this is the message returned when AxialMove is used in Assembly3 in the latest development versions of FreeCad. Since this hasn't been fixed yet, I'm reporting it here.
Kind regards.
 
```
Running the Python command 'asm3CmdAxialMove' failed:
Traceback (most recent call last):
  File "C:\Users\Bienvenue\AppData\Roaming\FreeCAD\Mod\FreeCAD_assembly3-master\.\freecad\asm3\gui.py", line 534, in Activated
    mover.movePart(False,AsmCmdMove._moveInfo)
  File "C:\Users\Bienvenue\AppData\Roaming\FreeCAD\Mod\FreeCAD_assembly3-master\.\freecad\asm3\mover.py", line 391, in movePart
    vobj.UseCenterballDragger = useCenterballDragger
    ^^^^^^^^^^^^^^^^^^^^^^^^^

'Gui.ViewProviderLink' object has no attribute 'UseCenterballDragger'
```

### Full version info

```shell
OS: Windows 10 build 19043
Architecture: x86_64
Version: 1.1.0dev.42180 (Git)
Build date: 2025/06/16 16:25:59
Build type: Release
Branch: main
Hash: fca41e4003f1680cf604b593a046ac2b1db6ba8a
Python 3.11.13, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.2.5, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: French/France (fr_FR)
Navigation Style/Orbit Style/Rotation Mode: CAD/Trackball/Drag at cursor
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/fusion
Logical DPI/Physical DPI/Pixel Ratio: 96/81.5973/1
Installed mods: 
  * DynamicData 2.70.0
  * fasteners 0.5.36
  * freecad.gears 1.3.0
  * FreeCAD_assembly3-master 0.12.2
```

### Subproject(s) affected?

None

### Anything else?

It works correctly in the 1.0.0 version.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Assembly 3 tickets should be opened at https://github.com/realthunder/FreeCAD_assembly3
