### PR TITLE
fix: handle missing identification attribute for IFC2X3 compatibility

### LINKED ISSUE #28997: BIM: Error when opening IFC 2x3 version with classification references
### Problem description

Unable to open/import IFC file, 2x3 schema version, with classification references.

I am not able to reproduce the issue with 4.0 version scheme.
I am not able to reproduce with FC 1.0 - it is a regression.
I am able to reproduce with FC 1.1 - the fix should be backported.

### Workbench affected?

BIM

### Steps to reproduce

- open FreeCAD in safe mode
- open sample IFC with (remove the .txt extension)

[bonsai-2x3-wall.ifc.txt](https://github.com/user-attachments/files/26440230/bonsai-2x3-wall.ifc.txt)

- change the import settings to `All individual IFC obejcts`
- click OK

### Expected behavior

IFC file should be opened.

### Actual behavior

- error message shows up

Image

- error from the report view

```
16:23:46  pyException: Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/tmp/.mount_FreeCANBinom/usr/lib/python3.11/site-packages/freecad/module_io.py", line 18, in OpenInsertObject
    getattr(importerModule, importMethod)(objectPath, *importArgs, **importKwargs)
  File "/tmp/.mount_FreeCANBinom/usr/Mod/BIM/nativeifc/ifc_import.py", line 55, in open
    insert(filename, doc.Name, singledoc=None)
  File "/tmp/.mount_FreeCANBinom/usr/Mod/BIM/nativeifc/ifc_import.py", line 93, in insert
    prj_obj = ifc_tools.create_document_object(document, filename, shapemode, strategy)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/.mount_FreeCANBinom/usr/Mod/BIM/nativeifc/ifc_tools.py", line 118, in create_document_object
    create_children(obj, ifcfile, recursive=True, assemblies=False)
  File "/tmp/.mount_FreeCANBinom/usr/Mod/BIM/nativeifc/ifc_tools.py", line 357, in create_children
    result.extend(create_child(obj, child))
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/.mount_FreeCANBinom/usr/Mod/BIM/nativeifc/ifc_tools.py", line 337, in create_child
    subresult.extend(create_child(child, building))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/.mount_FreeCANBinom/usr/Mod/BIM/nativeifc/ifc_tools.py", line 348, in create_child
    create_children(child, ifcfile, recursive, only_structure, assemblies)
  File "/tmp/.mount_FreeCANBinom/usr/Mod/BIM/nativeifc/ifc_tools.py", line 357, in create_children
    result.extend(create_child(obj, child))
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/.mount_FreeCANBinom/usr/Mod/BIM/nativeifc/ifc_tools.py", line 348, in create_child
    create_children(child, ifcfile, recursive, only_structure, assemblies)
  File "/tmp/.mount_FreeCANBinom/usr/Mod/BIM/nativeifc/ifc_tools.py", line 357, in create_children
    result.extend(create_child(obj, child))
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/.mount_FreeCANBinom/usr/Mod/BIM/nativeifc/ifc_tools.py", line<class 'AttributeError'>: entity instance of type 'IFC2X3.IfcClassificationReference' has no attribute 'Identification'
```

### Development version About Info (in Safe Mode)

```shell
OS: Debian GNU/Linux 13 (trixie) (GNOME/gnome-xorg/xcb)
Architecture: x86_64
Version: 1.2.0dev.20260311 (Git shallow) AppImage
Build date: 2026/03/11 07:18:44
Build type: Release
Branch: (HEAD detached at 03fc08d02)
Hash: 03fc08d02ebbafa0dc7268d8a7f89e17d3b4db87
Python 3.11.14, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: English/Ireland (en_IE)
Navigation Style/Orbit Style/Rotation Mode: CAD/Rounded Arcball/Window center
Stylesheet/Theme/QtStyle: FreeCAD.qss/FreeCAD Light/
Logical DPI/Physical DPI/Pixel Ratio: 96/92.6073/1
```

### Last known good version (optional)

```shell

```

### PR DESCRIPTION
**Pull request by caio-venancio**
## Issues

fixes #28997.

## Brief Summary
In `ifc_tools.py,` `add_properties(...)` assumes .Identification exists in `RelatingClassification`. However, this attribute is only available in IFC4, while IFC2X3 uses ItemReference. Now with the changes, it checks whether `RelatingClassification` has .Identification or .ItemReference, and if it does, it adds to Classification, working with IFC4.0 and IFC2X3 normally.

### CODE REVIEW

**Comment by freecad-ci-runner** [comment]
Successfully created backport PR for `releases/FreeCAD-1-1`:
- #29329

**Comment by caio-venancio** [comment]
Thanks for the feedback! I'm happy to help :)
