### PR TITLE
CAM: Profile - Select object in document tree

### LINKED ISSUE #24189: CAM: Profile OP generates more path than selected bodies
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Problem description

When selecting a Job model body from tree view it should make profile operation for that
body only. at the moment it profiles all the bodies in the Job. Makes using helper bodies harder than it should.

Image

### Full version info

```shell
OS: Ubuntu Core 22 (ubuntu:GNOME/ubuntu/wayland)
Architecture: x86_64
Version: 1.1.0dev.43611 (Git) Snap 1742
Build date: 2025/09/23 05:03:49
Build type: Release
Branch: main
Hash: c3707cc4a519a2b14d6dde3dadde525b3ba5350f
Python 3.10.12, Qt 5.15.15, Coin 4.0.0, Vtk 9.1.0, boost 1_74, Eigen3 3.4.0, PySide 5.15.11
shiboken 5.15.11, SMESH 7.7.1.0, xerces-c 3.2.3, IfcOpenShell 0.8.2, OCC 7.7.1
Locale: Estonian/Estonia (et_EE)
Navigation Style/Orbit Style/Rotation Mode: Blender/Rounded Arcball/Window center
Stylesheet/Theme/QtStyle: FreeCAD.qss/FreeCAD Light/Fusion
Logical DPI/Physical DPI/Pixel Ratio: 96/159.34/1
```

### Subproject(s) affected?

CAM

### Anything else?

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by tarman3**
Allows add models as Base to `Profile` operation without sub selection

Fixes #24189
- #24189

---

### Changes
- Replaced legacy <ins>PathOp.FeatureBase**Panels**</ins> by <ins>PathOp.FeatureBase**Models**</ins>
- Only GUI touched here, because processing models already included in #27236 

---

https://github.com/user-attachments/assets/401f8c89-0222-427c-96e2-2ea6252678fa

### CODE REVIEW

**Comment by jffmichi** [comment]
This breaks for the simplest case when profiling an edge:

[profile_edge_fail.zip](https://github.com/user-attachments/files/22542867/profile_edge_fail.zip)

profile_edge_fail

**Comment by tarman3** [comment]
Hope fixed

**Comment by jffmichi** [comment]
> Hope fixed

can confirm 👍

**Comment by jffmichi** [comment]
I'm getting an error when I have the Job selected and click on the Profile operation:
```
02:17:47  pyException: Traceback (most recent call last):
  File "/usr/lib/freecad/Mod/CAM/Path/Op/Base.py", line 528, in onChanged
    if prop == "Base" and self.sanitizeBase(obj):
  File "/usr/lib/freecad/Mod/CAM/Path/Op/Base.py", line 712, in sanitizeBase
    o.Shape.getElement(sub)
<class 'AttributeError'>: 'FeaturePython' object has no attribute 'Shape'
02:17:47  pyException: Traceback (most recent call last):
  File "/usr/lib/freecad/Mod/CAM/Path/Op/Base.py", line 532, in onChanged
    self.updateDepths(obj, True)
  File "/usr/lib/freecad/Mod/CAM/Path/Op/Base.py", line 661, in updateDepths
    bb = base.Shape.BoundBox
<class 'AttributeError'>: 'FeaturePython' object has no attribute 'Shape'
02:17:47  pyException: Traceback (most recent call last):
  File "/usr/lib/freecad/Mod/CAM/Path/Op/Base.py", line 532, in onChanged
    self.updateDepths(obj, True)
  File "/usr/lib/freecad/Mod/CAM/Path/Op/Base.py", line 661, in updateDepths
    bb = base.Shape.BoundBox
<class 'AttributeError'>: 'FeaturePython' object has no attribute 'Shape'
02:17:47  pyException: Traceback (most recent call last):
  File "/usr/lib/freecad/Mod/CAM/Path/Op/Gui/Base.py", line 109, in setEdit
    self.setupTaskPanel(
  File "/usr/lib/freecad/Mod/CAM/Path/Op/Gui/Base.py", line 122, in setupTaskPanel
    panel.setupUi()
  File "/usr/lib/freecad/Mod/CAM/Path/Op/Gui/Base.py", line 1388, in setupUi
    self.panelSetFields()
  File "/usr/lib/freecad/Mod/CAM/Path/Op/Gui/Base.py", line 1343, in panelSetFields
    self.obj.Proxy.sanitizeBase(self.obj)
  File "/usr/lib/freecad/Mod/CAM/Path/Op/Base.py", line 712, in sanitizeBase
    o.Shape.getElement(sub)
<class 'AttributeError'>: 'FeaturePython' object has no attribute 'Shape'
```
[Bildschirmaufnahme_20251010_021744.webm](https://github.com/user-attachments/assets/5ceb6de8-b820-4bc6-9e68-a75848a66829)

**Comment by tarman3** [comment]
Please check again

**Comment by jffmichi** [comment]
Seems to work. Unfortunately I'm getting a merge conflict with #22304

**Comment by tarman3** [comment]
If you try to merge this PR, no any sense to merge #22304

**Comment by jffmichi** [comment]
Are you saying the changes from #22304 are contained in this PR? From the title they seem to do two different things.

**Comment by tarman3** [comment]
Yes
But this PR based on commit from #22304, because they change the same file
Maybe there is some difference now, and that why get merge conflicts
Just use only this PR
