### ISSUE TITLE
Compilation error TaskFeatureParameters.cpp: 'QString::QString': cannot access private member declared in class 'QString'

### ISSUE THREAD

**Issue by ebswift** [FreeCAD/FreeCAD#24729]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Problem description

Compile breaks with 'QString::QString': cannot access private member declared in class 'QString' in TaskFeatureParameters.cpp.

Reported for lines 203 & 204 of TaskFeatureParameters.cpp

### Full version info

```shell
OS: Windows 11 build 26200
Architecture: x86_64
Version: 1.1.0dev.43968 (Git)
Build date: 2025/10/17 21:34:07
Build type: Release
Branch: main
Hash: 171389d9d3e93b43b742fa74b640545990bb4b42
Python 3.12.10, Qt 6.8.3, Coin 4.0.3, Vtk 9.4.2, boost 1_87, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, SMESH 7.7.1.0, xerces-c 3.2.5, IfcOpenShell 0.8.1.post1, OCC 7.8.1
Locale: English/Australia (en_AU)
Navigation Style/Orbit Style/Rotation Mode: TinkerCAD/Trackball/Drag at cursor
Stylesheet/Theme/QtStyle: OpenLight.qss/OpenLight/
Logical DPI/Physical DPI/Pixel Ratio: 96/92.6073/1
Installed mods: 
  * Gridfinity 0.11.9
  * OpenTheme 2025.5.20
```

### Subproject(s) affected?

None

### Anything else?

possibly introduced with Commit 65d166f

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
