### ISSUE TITLE
[Compilation Lost compatibility with Qt5

### ISSUE THREAD

**Issue by galou** [FreeCAD/FreeCAD#27248]
### Problem description

Cannot build with Qt5.15 due to the use of `QList.emplace_back()` in TechDraw:
```
[ 85%] Building CXX object src/Mod/TechDraw/Gui/CMakeFiles/TechDrawGui.dir/QGIProjGroup.cpp.o
/home/gael/04-sources/freecad/FreeCAD/src/Mod/TechDraw/Gui/QGIProjGroup.cpp: In member function ‘QList<TechDrawGui::QGIViewPart*> TechDrawGui::QGIProjGroup::secondaryQViews() const’:
/home/gael/04-sources/freecad/FreeCAD/src/Mod/TechDraw/Gui/QGIProjGroup.cpp:249:16: error: ‘class QList<TechDrawGui::QGIViewPart*>’ has no member named ‘emplace_back’
  249 |         result.emplace_back(qview);
      |                ^~~~~~~~~~~~
```

According to https://doc.qt.io/archives/qt-5.15/qlist.html the method is not implemented.

### Workbench affected?

TechDraw

### Steps to reproduce

1. `make`

### Expected behavior

Should compile with Qt5.15.

### Actual behavior

Cf. above error.

### Development version About Info (in Safe Mode)

```shell
The culprit is commit fd014445fbfb.
```

### Last known good version (optional)

```shell
Commit 5d4495785b72?
```

**Comment by Lgt2x** [comment]
@kadet1090 was Qt5 compatibility officially dropped?

**Comment by Lgt2x** [comment]
In any case, Qt5 compilation is not tested on CI anymore, so this is bound to happen again

**Comment by kadet1090** [comment]
> [@kadet1090](https://github.com/kadet1090) was Qt5 compatibility officially dropped?

Basically policy is that we don't yet fully abandon it like removing all conditional compilation that allows us to still build it on Qt5 but we are not making an effort to ensure that it compiles on Qt5 anymore. If someone is willing to put the effort and will to make it work, we will merge such changes but we won't treat it as priority to fix.

**Comment by furgo16** [comment]
https://forum.freecad.org/viewtopic.php?t=102292

**Comment by furgo16** [comment]
For the record, I'm also compiling with Qt 5 locally, knowing that this is not supported and expecting that it would break at some point. I did a full rebuild recently, but I believe it was before https://github.com/FreeCAD/FreeCAD/commit/fd014445fbfb

**Comment by Lgt2x** [comment]
`FREECAD_QT_VERSION` has not been removed yet, so I sent a fix
