### PR TITLE
Measure: Fix build failure of new MeasureDiameter

### PR DESCRIPTION
**Pull request by PaddleStroke**
Fix build failure caused by https://github.com/FreeCAD/FreeCAD/pull/24853

> -MT src/Mod/Measure/App/CMakeFiles/Measure.dir/AppMeasure.cpp.o -MF src/Mod/Measure/App/CMakeFiles/Measure.dir/AppMeasure.cpp.o.d -o src/Mod/Measure/App/CMakeFiles/Measure.dir/AppMeasure.cpp.o -c /Users/runner/work/FreeCAD/FreeCAD/src/Mod/Measure/App/AppMeasure.cpp
> In file included from /Users/runner/work/FreeCAD/FreeCAD/src/Mod/Measure/App/AppMeasure.cpp:46:
> Error: /Users/runner/work/FreeCAD/FreeCAD/src/Mod/Measure/App/MeasureDiameter.h:71:36: error: non-virtual member function marked 'override' hides virtual member function
>    71 |     Base::Placement getPlacement() override;
>       |                                    ^
> /Users/runner/work/FreeCAD/FreeCAD/src/App/DocumentObject.h:721:29: note: hidden overloaded virtual function 'App::DocumentObject::getPlacement' declared here: different qualifiers ('const' vs unqualified)
>   721 |     virtual Base::Placement getPlacement() const;
>       |                             ^
> 1 error generated.
> [1942/6738] Building CXX object src/Mod/Measure/App/CMakeFiles/Measure.dir/MeasureBase.cpp.o
> [1943/6738] Building CXX object src/Mod/Measure/App/CMakeFiles/Measure.dir/Measurement.cpp.o
> [1944/6738] Building CXX object src/Mod/Measure/App/CMakeFiles/Measure.dir/MeasureAngle.cpp.o
> [1945/6738] Building CXX object src/Mod/Measure/App/CMakeFiles/Measure.dir/MeasureDistance.cpp.o
> ninja: build stopped: subcommand failed.
> Error: Process completed with exit code 1.

### CODE REVIEW

**Comment by PaddleStroke** [comment]
@maxwxyz

**Comment by tarman3** [comment]
race condition
- #26719

**Comment by maxwxyz** [comment]
so both need to be merged?

**Comment by pieterhijma** [comment]
No, I think this one is better. My analysis of that it was unused is probably not right. I would still check with @kevinsmia1939 to be sure, but I would suggest to simply merge this one because that analysis can happen after the fact as well.

**Comment by furgo16** [comment]
I happened to rebase/merge a few of my old PRs today and all failed with this error.

Howcome did the CI workflows not catch the build failure on https://github.com/FreeCAD/FreeCAD/pull/24853 in the first place?

**Comment by PaddleStroke** [comment]
> Howcome did the CI workflows not catch the build failure on https://github.com/FreeCAD/FreeCAD/pull/24853 in the first place?

Because getPlacement has only recently been turned into a const.
User has not rebased his PR after that fact. So his PR was building OK.
And so the build failure appeared only after merge since in main getPlacement is const

**Comment by furgo16** [comment]
> And so the build failure appeared only after merge

Thanks for the clarification. My point was though, are the CI workflows not run automatically before the merge? Even if no-one (maintainer or author) rebased the PR manually (which, for a months-old PR might have been safest and would have caught the error).

**Comment by kadet1090** [comment]
> > And so the build failure appeared only after merge
> 
> Thanks for the clarification. My point was though, are the CI workflows not run automatically before the merge? Even if no-one (maintainer or author) rebased the PR manually (which, for a months-old PR might have been safest and would have caught the error).

They do but the PR was old and CI was executed on an old version of main - we do not reexecute each PR just before merge as this would kill our CI queue. I've put reminder for maintainers to rebase PRs that are aimed at 1.2 (as they are usually old) before merging to catch issues like this.

**Comment by ipatch** [comment]
> They do but the PR was old and CI was executed on an old version of main - we do not reexecute each PR just before merge as this would kill our CI queue. I've put reminder for maintainers to rebase PRs that are aimed at 1.2 (as they are usually old) before merging to catch issues like this.

eeeekkkk this does seem like an edge case that should be dealt with IMHO.

**Comment by kadet1090** [comment]
We are glad to hear solutions to problem like that (or even better - accept PRs). Keep in mind that we have limited CI resources and running jobs for PR and rebasing each PR before merge is simply quite unrealistic. We tried to have merge queue which would help with cases like that but it got stuck after like 1 day.
