### ISSUE TITLE
BIM: Error when Arch_Wall second point is inserted by keyboard

### ISSUE THREAD

**Issue by semhustej** [FreeCAD/FreeCAD#19324]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Problem description

Steps to reproduce:

- open FreeCAD in safe mode
- open new architecture/BIM project
- hit `Cancel` on the BIM welcome screen
- start Arch_Wall command
- click anywhere to select the first point
- move mouse a bit
- start typing numbers (which are inserted in the X coordinate)
- error message shows up

<details><summary>Error message</summary>

```
16:17:23  Traceback (most recent call last):
16:17:23    File "C:\Users\semhu\Documents\tyo\BF\FreeCAD\FC_daily\FreeCAD_weekly-builds-40006-conda-Windows-x86_64-py311\Mod\Draft\DraftGui.py", line 1108, in checkSpecialChars
16:17:23      self.updateSnapper()
16:17:23    File "C:\Users\semhu\Documents\tyo\BF\FreeCAD\FC_daily\FreeCAD_weekly-builds-40006-conda-Windows-x86_64-py311\Mod\Draft\DraftGui.py", line 1216, in updateSnapper
16:17:23      if self.relativeMode and self.sourceCmd.node:
16:17:23                               ^^^^^^^^^^^^^^^^^^^
16:17:23  AttributeError: 'NoneType' object has no attribute 'node'
16:17:23  Traceback (most recent call last):
16:17:23    File "C:\Users\semhu\Documents\tyo\BF\FreeCAD\FC_daily\FreeCAD_weekly-builds-40006-conda-Windows-x86_64-py311\Mod\Draft\DraftGui.py", line 1520, in changeXValue
16:17:23      self.updateSnapper()
16:17:23    File "C:\Users\semhu\Documents\tyo\BF\FreeCAD\FC_daily\FreeCAD_weekly-builds-40006-conda-Windows-x86_64-py311\Mod\Draft\DraftGui.py", line 1216, in updateSnapper
16:17:23      if self.relativeMode and self.sourceCmd.node:
16:17:23                               ^^^^^^^^^^^^^^^^^^^
16:17:23  AttributeError: 'NoneType' object has no attribute 'node'
16:17:23  Traceback (most recent call last):
16:17:23    File "C:\Users\semhu\Documents\tyo\BF\FreeCAD\FC_daily\FreeCAD_weekly-builds-40006-conda-Windows-x86_64-py311\Mod\Draft\DraftGui.py", line 1108, in checkSpecialChars
16:17:23      self.updateSnapper()
16:17:23    File "C:\Users\semhu\Documents\tyo\BF\FreeCAD\FC_daily\FreeCAD_weekly-builds-40006-conda-Windows-x86_64-py311\Mod\Draft\DraftGui.py", line 1216, in updateSnapper
16:17:23      if self.relativeMode and self.sourceCmd.node:
16:17:23                               ^^^^^^^^^^^^^^^^^^^
16:17:23  AttributeError: 'NoneType' object has no attribute 'node'
16:17:23  Traceback (most recent call last):
16:17:23    File "C:\Users\semhu\Documents\tyo\BF\FreeCAD\FC_daily\FreeCAD_weekly-builds-40006-conda-Windows-x86_64-py311\Mod\Draft\DraftGui.py", line 1520, in changeXValue
16:17:23      self.updateSnapper()
16:17:23    File "C:\Users\semhu\Documents\tyo\BF\FreeCAD\FC_daily\FreeCAD_weekly-builds-40006-conda-Windows-x86_64-py311\Mod\Draft\DraftGui.py", line 1216, in updateSnapper
16:17:23      if self.relativeMode and self.sourceCmd.node:
16:17:23                               ^^^^^^^^^^^^^^^^^^^
16:17:23  AttributeError: 'NoneType' object has no attribute 'node'
16:17:23  Traceback (most recent call last):
16:17:23    File "C:\Users\semhu\Documents\tyo\BF\FreeCAD\FC_daily\FreeCAD_weekly-builds-40006-conda-Windows-x86_64-py311\Mod\Draft\DraftGui.py", line 1108, in checkSpecialChars
16:17:23      self.updateSnapper()
16:17:23    File "C:\Users\semhu\Documents\tyo\BF\FreeCAD\FC_daily\FreeCAD_weekly-builds-40006-conda-Windows-x86_64-py311\Mod\Draft\DraftGui.py", line 1216, in updateSnapper
16:17:23      if self.relativeMode and self.sourceCmd.node:
16:17:23                               ^^^^^^^^^^^^^^^^^^^
16:17:23  AttributeError: 'NoneType' object has no attribute 'node'
16:17:23  Traceback (most recent call last):
16:17:23    File "C:\Users\semhu\Documents\tyo\BF\FreeCAD\FC_daily\FreeCAD_weekly-builds-40006-conda-Windows-x86_64-py311\Mod\Draft\DraftGui.py", line 1520, in changeXValue
16:17:23      self.updateSnapper()
16:17:23    File "C:\Users\semhu\Documents\tyo\BF\FreeCAD\FC_daily\FreeCAD_weekly-builds-40006-conda-Windows-x86_64-py311\Mod\Draft\DraftGui.py", line 1216, in updateSnapper
16:17:23      if self.relativeMode and self.sourceCmd.node:
16:17:23                               ^^^^^^^^^^^^^^^^^^^
16:17:23  AttributeError: 'NoneType' object has no attribute 'node'
16:17:29  Traceback (most recent call last):
16:17:29    File "C:\Users\semhu\Documents\tyo\BF\FreeCAD\FC_daily\FreeCAD_weekly-builds-40006-conda-Windows-x86_64-py311\Mod\Draft\DraftGui.py", line 1000, in checkx
16:17:29      self.updateSnapper()
16:17:29    File "C:\Users\semhu\Documents\tyo\BF\FreeCAD\FC_daily\FreeCAD_weekly-builds-40006-conda-Windows-x86_64-py311\Mod\Draft\DraftGui.py", line 1216, in updateSnapper
16:17:29      if self.relativeMode and self.sourceCmd.node:
16:17:29                               ^^^^^^^^^^^^^^^^^^^
16:17:29  AttributeError: 'NoneType' object has no attribute 'node'

```
<details>

### Full version info

```shell
OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.1.0dev.40006 (Git) Conda
Build type: Release
Branch: main
Hash: 11125be89d7ed063b706f633d36552849a22ef7e
Python 3.11.11, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/Fusion
```

### Subproject(s) affected?

BIM

### Anything else?

The error was not happening with the last weekly 1.1.0dev.39980. The error is not happening in FC 1.0.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Syres916** [comment]
You could try changing line 1216 of DraftGui.py (untested) from:

`            if self.relativeMode and self.sourceCmd.node:`

to:

`            if hasattr(self.sourceCmd,"node") and self.relativeMode:`

**Comment by semhustej** [comment]
> You could try changing line 1216 of DraftGui.py (untested) from:
> 
> ` if self.relativeMode and self.sourceCmd.node:`
> 
> to:
> 
> ` if hasattr(self.sourceCmd,"node") and self.relativeMode:`

I can confirm I get no error message after I did this change on my machine.

**Comment by paullee0** [comment]
So the fix is available?

**Comment by Syres916** [comment]
> So the fix is available?

It would be best if @Roy-043 could please clarify if the fix is acceptable, i.e. doesn't introduce a regression. If it's OK then I can submit a PR.

**Comment by Roy-043** [comment]
The issue is a regression introduced with #19179. #19343 should fix it.

**Comment by paullee0** [comment]
I got below error, if I checked (unchecked it first) the Relative checkbox, after first point of Wall was selected.  Relevant or separate bug?

```
08:18:50  Traceback (most recent call last):
08:18:50    File "/home/paullee/Downloads/FreeCAD/FreeCAD_1.0_&_post/FreeCAD_weekly-builds-40006-conda-Linux-x86_64-py311/squashfs-root/usr/Mod/Draft/DraftGui.py", line 970, in setRelative
08:18:50      self.updateSnapper()
08:18:50    File "/home/paullee/Downloads/FreeCAD/FreeCAD_1.0_&_post/FreeCAD_weekly-builds-40006-conda-Linux-x86_64-py311/squashfs-root/usr/Mod/Draft/DraftGui.py", line 1216, in updateSnapper
08:18:50      if self.relativeMode and self.sourceCmd.node:
08:18:50                               ^^^^^^^^^^^^^^^^^^^
08:18:50  AttributeError: 'NoneType' object has no attribute 'node'

```

**Comment by Roy-043** [comment]
> Relevant or separate bug?

This is the same error as in the original report (please expand the Error message section).
