### PR TITLE
how to build on armhf BQ M10 Ubuntu Tablet 

### PR DESCRIPTION
**Pull request by 243750496**
Q1: i have compiled vtk 6.3.0 and installed on arm then the tips show up: 
-- VTK components: not found or used
do that is an error? 

Q2:why it goes on with such an error and finished compile before 'make' step

Q3:Whether the error below cause of the reason of VTK not found???
```

/DriverMED_Family.cpp.o
In file included from /usr/include/hdf5/openmpi/hdf5.h:24:0,
                 from /home/phablet/Downloads/Freecad/src/3rdParty/salomesmesh/inc/MED_Common.hxx:32,
                 from /home/phablet/Downloads/Freecad/src/3rdParty/salomesmesh/inc/DriverMED_Family.h:37,
                 from /home/phablet/Downloads/Freecad/src/3rdParty/salomesmesh/src/SMESH/DriverMED_Family.cpp:28:
/usr/include/hdf5/openmpi/H5public.h:61:20: fatal error: mpi.h: No such file or directory
 #   include <mpi.h>
                    ^
compilation terminated.
src/3rdParty/salomesmesh/CMakeFiles/SMESH.dir/build.make:146: recipe for target 'src/3rdParty/salomesmesh/CMakeFiles/SMESH.dir/src/SMESH/DriverMED_Family.cpp.o' failed
make[2]: *** [src/3rdParty/salomesmesh/CMakeFiles/SMESH.dir/src/SMESH/DriverMED_Family.cpp.o] Error 1
CMakeFiles/Makefile2:500: recipe for target 'src/3rdParty/salomesmesh/CMakeFiles/SMESH.dir/all' failed
make[1]: *** [src/3rdParty/salomesmesh/CMakeFiles/SMESH.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2

phablet@ubuntu-phablet:~/Downloads/FD$ cmake ../Freecad
-- prefix: /usr/local
-- datadir: data
-- docdir: doc
-- includedir: include
-- libdir: /usr/local/lib
-- Boost version: 1.55.0
-- Found the following Boost libraries:
--   filesystem
--   program_options
--   regex
--   signals
--   system
--   thread
-- Found Xerces-C: /usr/lib/arm-linux-gnueabihf/libxerces-c.so
-- PyCXX found:
--   Headers:  /home/phablet/Downloads/Freecad/src
--   Sources:  /home/phablet/Downloads/Freecad/src/CXX
-- -- OpenCASCADE Community Edition has been found.
-- -- Found OCE/OpenCASCADE version: 6.7.0
-- -- OCE/OpenCASCADE include directory: /usr/lib/arm-linux-gnueabihf/oce-0.15/../../../include/oce
-- -- OCE/OpenCASCADE shared libraries directory: 
-- VTK components: not found or used
-- Check for medfile (libmed and libmedc) ...
-- checking for module 'Coin'
--   package 'Coin' not found
-- libshiboken built for Release
-- Found PySide Tools: /usr/bin/pyside-uic, /usr/bin/pyside-rcc
-- -- matplotlib-1.4.2 has been found.
-- Platform is 32-bit
-- Build type: 
sh: 1: git: not found
sh: 1: bzr: not found
sh: 1: svnversion: not found
sh: 1: svn: not found
Unknown version control
/home/phablet/Downloads/FD/src/Build/Version.h written
-- setting gcc options: -Wall -Werror -Wno-deprecated -pedantic-errors
-- Boost version: 1.55.0
-- Found the following Boost libraries:
--   python
-- found Boost: 1_55
-- boost-incude dirs are: /usr/include
-- boost-python lib is: /usr/lib/arm-linux-gnueabihf/libboost_python.so
-- boost_LIBRARY_DIRS is: /usr/lib/arm-linux-gnueabihf
-- Boost_LIBRARIES is: /usr/lib/arm-linux-gnueabihf/libboost_python.so
-- area module (for Path Workbench) will be installed to: /usr/local/lib
-- Note: Doxygen docs will look better with graphviz's dot installed.
-- Coin3D doc is not installed
=======================================
Now run 'make' to build FreeCAD
=======================================

-- Configuring done


-- Generating done
-- Build files have been written to: /home/phablet/Downloads/FD
phablet@ubuntu-phablet:~/Downloads/FD$ 
phablet@ubuntu-phablet:~/Downloads/FD$ 
phablet@ubuntu-phablet:~/Downloads/FD$ make
[  0%] Built target Driver
[  1%] Built target SMDS
[  1%] Built target DriverDAT
[  1%] Built target DriverSTL
[  1%] Built target SMESHDS
[  2%] Built target DriverUNV
[  2%] Built target MEFISTO2
[  3%] Building CXX object src/3rdParty/salomesmesh/CMakeFiles/SMESH.dir/src/SMESH/DriverMED_Family.cpp.o
In file included from /usr/include/hdf5/openmpi/hdf5.h:24:0,
                 from /home/phablet/Downloads/Freecad/src/3rdParty/salomesmesh/inc/MED_Common.hxx:32,
                 from /home/phablet/Downloads/Freecad/src/3rdParty/salomesmesh/inc/DriverMED_Family.h:37,
                 from /home/phablet/Downloads/Freecad/src/3rdParty/salomesmesh/src/SMESH/DriverMED_Family.cpp:28:
/usr/include/hdf5/openmpi/H5public.h:61:20: fatal error: mpi.h: No such file or directory
 #   include <mpi.h>
                    ^
compilation terminated.
src/3rdParty/salomesmesh/CMakeFiles/SMESH.dir/build.make:146: recipe for target 'src/3rdParty/salomesmesh/CMakeFiles/SMESH.dir/src/SMESH/DriverMED_Family.cpp.o' failed
make[2]: *** [src/3rdParty/salomesmesh/CMakeFiles/SMESH.dir/src/SMESH/DriverMED_Family.cpp.o] Error 1
CMakeFiles/Makefile2:500: recipe for target 'src/3rdParty/salomesmesh/CMakeFiles/SMESH.dir/all' failed
make[1]: *** [src/3rdParty/salomesmesh/CMakeFiles/SMESH.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2
phablet@ubuntu-phablet:~/Downloads/FD$ 

```
BTW: All build on Ubuntu Tablet BQ M10 15.04 OTA-14 ARMhf
and libsoqt4-dev libcoin60-doc python-pivy these three depends i haven't found arm version and cannot build from source on arm so do this lead to the problem??

i havent found any useful artical on how to build freecad on armhf so i wish i could get ur help, Thx!

### CODE REVIEW

**Comment by wwmayer** [comment]
What's the sense of making a PR with merge conflicts and changes that are in master already for a long time, anyway? If you have build problems then you should visit the forum and ask your questions there.
