### PR TITLE
Gui: Fix Shiboken version detection and compilation error

### PR DESCRIPTION
**Pull request by wavexx**
- Shiboken headers need to be included first to get MAJOR/MINOR version flags. Without them the code would still compile, but fail the version check a few lines below assuming Shiboken is always older than 5.12
- Fix typo in cast when HAVE_SHIBOKEN_TYPE_FOR_TYPENAME is defined and remove the conditional: we have to assume typeForTypeName() always results in a valid name, as for the other implementations. There's no error handling of any kind in callers.

This fixes the build on debian unstable with shiboken 5.15.

### CODE REVIEW

**Comment by chennes** [comment]
Presumably on some platforms this include file is being transiently brought in, so we haven't run into this error. I can't confirm that the change fixes anything, but it does not break my compilation on any platform, and it seems sane.

**Comment by wavexx** [comment]
Maybe we should ensure the version macro is define instead of failing the version check silently, which is why I suspect was failing silently. There's a fix in the code that should have been enabled compilation error, so my guess is that nobody ever compiled that branch so far.

Should I introduce the extra check?
