### PR TITLE
Draft: fix Bspline regression caused by #29222

### LINKED ISSUE #29770: Draft: Bspline Part.Shape' object has no attribute 'tangentAt' error
### Problem description

When I draw a spline gives error message

Related:https://github.com/FreeCAD/FreeCAD/issues/29745

### Workbench affected?

Draft

### Steps to reproduce

https://github.com/user-attachments/assets/86d7123a-d5fb-4058-bbc2-10a41ec875ea

### Expected behavior

*

### Actual behavior

*

### Development version About Info (in Safe Mode)

```shell
OS: Windows 11 build 26200
Architecture: x86_64
Version: 1.2.0dev.20260429 (Git shallow)
Build date: 2026/04/29 07:07:16
Build type: Release
Branch: grafted,grafted
Hash: a785d40ac4c37f559b0b82fbaf9bf7dc68a468e4
Python 3.11.15, Qt 6.8.3, Coin 4.0.8, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: Turkish/Türkiye (tr_TR) [ OS: Turkish/Türkiye (tr_TR) ]
Stylesheet/Theme/QtStyle: FreeCAD.qss/FreeCAD Dark/
Navigation Style/Orbit Style/Rotation Mode: Blender/Rounded Arcball/Window center
Logical DPI/Physical DPI/Pixel Ratio: 96/81.5973/1
Installed mods:
  * Curves workbench 0.6.70
```

### Last known good version (optional)

```shell
1.1.1

```

### PR DESCRIPTION
**Pull request by Roy-043**
Fixes #29770.

See: https://github.com/FreeCAD/FreeCAD/issues/29770#issuecomment-4378085405

### CODE REVIEW

**Comment by FEA-eng** [comment]
This PR fixes the error when finishing B-spline, but I still get an equivalent error when closing it (shortcut O):

```
18:27:23  pyException: Traceback (most recent call last):
  File "D:\FreeCAD_dev\FreeCAD-src\.pixi\envs\default\Library\Mod\Draft\draftviewproviders\view_wire.py", line 126, in updateData
    v1 = rot.multVec(shp.tangentAt(shp.FirstParameter))
                     ^^^^^^^^^^^^^
<class 'AttributeError'>: 'Part.Wire' object has no attribute 'tangentAt'
```

**Comment by Roy-043** [comment]
Thanks for testing. I was so focused on start and end arrows that I only tested with open B-splines (my bad). I have updated the code and this should be fixed now. The position and alignment of end arrows for closed shapes has also been corrected.

I still have to check how the SVG related code deals with this. I have therefore switched this to draft.

**Comment by Roy-043** [comment]
SVG code has been updated as well now.

**Review by FEA-eng — APPROVED** [review]
@maxwxyz Tested, fixes the issue
