### ISSUE TITLE
Packaging: freecad v1.1 arm64 build failure - netgen

### ISSUE THREAD

**Issue by brettowe** [FreeCAD/FreeCAD#29163]
### Problem description

while working on the 1.1 package for opensuse I found that the arm build is failing with the following error.

/usr/include/netgen/core/simd_arm64.hpp:161:28: error: cannot convert ‘__Int64x2_t’ to ‘uint64x2_t’

full log attached
[freecad1.1-aarch64-netgen.log](https://github.com/user-attachments/files/26555585/freecad1.1-aarch64-netgen.log)

### Workbench affected?

None

### Steps to reproduce

build on opensuse arm

### Expected behavior

.

### Actual behavior

[freecad1.1-aarch64-netgen.log](https://github.com/user-attachments/files/26555585/freecad1.1-aarch64-netgen.log)

### Development version About Info (in Safe Mode)

```shell
working from released 1.1 source tarball
```

### Last known good version (optional)

```shell

```
