### PR TITLE
Gui: SplashSreen: restore visibility

### LINKED ISSUE #16264: New SplashScreen only gets displayed for a fraction of a second.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Looks like all the loading gets performed and after that the splash appears for a blink of an eye.

https://github.com/user-attachments/assets/ed066d97-e502-4a78-b62a-e463d5653db0

### Full version info

```shell
OS: Arch Linux (GNOME/gnome)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38622 (Git) AppImage
Build type: Release
Branch: main
Hash: ed97f3c4591303ee3b54906768f8f4eba5211265
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Installed mods: 
  * OpenTheme 2024.8.17
```

### Subproject(s) affected?

None

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by 3x380V**
Work around problems exposed by QTBUG-119225 and its fix both in Qt and FreeCAD code. Note that 250ms is arbitrarily choosen timeout never reached in practice; while loop terminates in first or second pass.

Unlike `QSplashScreen`, this `SplashScreen` is actually waiting for `isExposed()`. Refer to [1](https://github.com/qt/qtbase/blob/d8046ecc6efa84a180a42e3a724dcea43ac88249/src/gui/kernel/qwindow.cpp#L81-L93) and [2](https://github.com/qt/qtbase/commit/7835f9e60157987b4aafc9b860f925d775151b7c) for details.

Fixes: #16264

- [x] This PR is verified human output and it is ridiculous to demand such a checkbox instead simple S-o-b line known for ages and introduced for such purposes.

> [!NOTE]
> Although this PR fixes issue caused by #29917 for me, I do not want it merged. Actually #29917 is the very first change tacking the core of the problems reported in #16264 and needs only minor adjustments. Historically log output was always part of the splash screen, message after message appearing at the bottom of the splash in the 50ms intervals. Those intervals caused considerable startup slowdown while splash was shown, so people started inventing various shortcuts to overcome that (first disabling slash by default then disabling log output by default). I still do think idea introduced in #16334 is a way to go and I would be happy to be reconsidered (each logged line triggers `processEvents()` making it automagically work).

### CODE REVIEW

**Comment by ElementW** [comment]
Is there a reason you don't want this merged? The fix looks and tests fine for me (the splash does display earlier as would be expected), and is arguably how I should've done this from the get go.

The loop does not meaningfully sleep-stall the main thread so it's all good.
image

**Comment by 3x380V** [comment]
As mentioned I'd rather see #16334 merged instead. But since it is actually based on this one, lets remove Draft status and wait what happens next. And of course, thanks for testing (and providing previous fix)!

**Comment by Lgt2x** [comment]
@3x380V Windows CI build is failing, probably a missing include 

```
2026-07-08T07:20:56.3207795Z     79>ClCompile:
2026-07-08T07:20:56.3208247Z          SplashScreen.cpp
2026-07-08T07:20:56.3473858Z    150>ClCompile:
2026-07-08T07:20:56.3474306Z          mocs_compilation_Release.cpp
2026-07-08T07:20:56.3537997Z     79>D:\a\FreeCAD\FreeCAD\src\Gui\SplashScreen.cpp(283,9): error C3861: 'Sleep': identifier not found [C:\FC\build\release\src\Gui\FreeCADGui.vcxproj]
```

**Comment by ElementW** [comment]
@3x380V Just use `std::this_thread::sleep_for()` instead of platform specific calls

**Comment by 3x380V** [comment]
@ElementW, after all not being fan of mixing _std_ and _Qt_ calls I used `QThread::msleep()`

**Review by Lgt2x — APPROVED** [review]
I can't see a difference with or without this PR on my setup, but multiple people have confirmed that this solves the issue, so let's roll with it! Thanks again for your in-depth investigation

**Comment by Lgt2x** [comment]
Merging this before the more complete fix in #16334
