### PR TITLE
TechDraw: Potential fix for snap builds, specify type

### LINKED ISSUE #20820: Snap daily build failure 2025-04-16
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Problem description

The snap daily build failed yesterday: https://github.com/FreeCAD/FreeCAD-snap/actions/runs/14482259726/job/40621422608#step:3:9555

The log extract:

<details>

```
:: /root/parts/freecad/src/src/Mod/TechDraw/Gui/CommandExtensionDims.cpp:2065:44: error: no matching function for call to ‘toDegrees(int)’
::  2065 |         float alpha = round(Base::toDegrees(abs(atan(dy / dx))));
::       |                             ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
:: In file included from /root/parts/freecad/src/src/Mod/TechDraw/Gui/CommandExtensionDims.cpp:36:
:: /root/parts/freecad/src/src/Base/Tools.h:151:13: note: candidate: ‘template<class T>  requires  floating_point<T> constexpr T Base::toDegrees(T)’
::   151 | constexpr T toDegrees(T radians)
::       |             ^~~~~~~~~
:: /root/parts/freecad/src/src/Base/Tools.h:151:13: note:   template argument deduction/substitution failed:
:: /root/parts/freecad/src/src/Base/Tools.h:151:13: note: constraints not satisfied
:: In file included from /usr/include/c++/11/compare:39,
::                  from /usr/include/c++/11/bits/stl_pair.h:65,
::                  from /usr/include/c++/11/utility:70,
::                  from /snap/kde-qt5-core22-sdk/1/usr/include/x86_64-linux-gnu/qt5/QtCore/qglobal.h:47,
::                  from /snap/kde-qt5-core22-sdk/1/usr/include/x86_64-linux-gnu/qt5/QtGui/qtguiglobal.h:43,
::                  from /snap/kde-qt5-core22-sdk/1/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtwidgetsglobal.h:43,
::                  from /snap/kde-qt5-core22-sdk/1/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qapplication.h:43,
::                  from /snap/kde-qt5-core22-sdk/1/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QApplication:1,
::                  from /root/parts/freecad/src/src/Mod/TechDraw/Gui/CommandExtensionDims.cpp:25:
:: /usr/include/c++/11/concepts: In substitution of ‘template<class T>  requires  floating_point<T> constexpr T Base::toDegrees(T) [with T = int]’:
:: /root/parts/freecad/src/src/Mod/TechDraw/Gui/CommandExtensionDims.cpp:2065:44:   required from here
:: /usr/include/c++/11/concepts:109:13:   required for the satisfaction of ‘floating_point<T>’ [with T = int]
:: /usr/include/c++/11/concepts:109:30: note: the expression ‘is_floating_point_v<_Tp> [with _Tp = int]’ evaluated to ‘false’
::   109 |     concept floating_point = is_floating_point_v<_Tp>;
::       |                              ^~~~~~~~~~~~~~~~~~~~~~~~
:: In file included from /root/parts/freecad/src/src/Mod/TechDraw/Gui/CommandExtensionDims.cpp:36:
:: /root/parts/freecad/src/src/Base/Tools.h:160:13: note: candidate: ‘template<class T>  requires (is_arithmetic_v<T>) && !(floating_point<T>) constexpr T Base::toDegrees(std::type_identity_t<T>)’
::   160 | constexpr T toDegrees(std::type_identity_t<T> radians)
::       |             ^~~~~~~~~
:: /root/parts/freecad/src/src/Base/Tools.h:160:13: note:   template argument deduction/substitution failed:
:: /root/parts/freecad/src/src/Mod/TechDraw/Gui/CommandExtensionDims.cpp:2065:44: note:   couldn’t deduce template parameter ‘T’
::  2065 |         float alpha = round(Base::toDegrees(abs(atan(dy / dx))));
::       |                             ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
:: /root/parts/freecad/src/src/Mod/TechDraw/Gui/CommandExtensionDims.cpp: In function ‘void execCreateVertChamferDimension(Gui::Command*)’:
:: /root/parts/freecad/src/src/Mod/TechDraw/Gui/CommandExtensionDims.cpp:2133:44: error: no matching function for call to ‘toDegrees(int)’
::  2133 |         float alpha = round(Base::toDegrees(abs(atan(dx / dy))));
::       |                             ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
:: In file included from /root/parts/freecad/src/src/Mod/TechDraw/Gui/CommandExtensionDims.cpp:36:
:: /root/parts/freecad/src/src/Base/Tools.h:151:13: note: candidate: ‘template<class T>  requires  floating_point<T> constexpr T Base::toDegrees(T)’
::   151 | constexpr T toDegrees(T radians)
::       |             ^~~~~~~~~
:: /root/parts/freecad/src/src/Base/Tools.h:151:13: note:   template argument deduction/substitution failed:
:: /root/parts/freecad/src/src/Base/Tools.h:151:13: note: constraints not satisfied
:: In file included from /usr/include/c++/11/compare:39,
::                  from /usr/include/c++/11/bits/stl_pair.h:65,
::                  from /usr/include/c++/11/utility:70,
::                  from /snap/kde-qt5-core22-sdk/1/usr/include/x86_64-linux-gnu/qt5/QtCore/qglobal.h:47,
::                  from /snap/kde-qt5-core22-sdk/1/usr/include/x86_64-linux-gnu/qt5/QtGui/qtguiglobal.h:43,
::                  from /snap/kde-qt5-core22-sdk/1/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtwidgetsglobal.h:43,
::                  from /snap/kde-qt5-core22-sdk/1/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qapplication.h:43,
::                  from /snap/kde-qt5-core22-sdk/1/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QApplication:1,
::                  from /root/parts/freecad/src/src/Mod/TechDraw/Gui/CommandExtensionDims.cpp:25:
:: /usr/include/c++/11/concepts: In substitution of ‘template<class T>  requires  floating_point<T> constexpr T Base::toDegrees(T) [with T = int]’:
:: /root/parts/freecad/src/src/Mod/TechDraw/Gui/CommandExtensionDims.cpp:2133:44:   required from here
:: /usr/include/c++/11/concepts:109:13:   required for the satisfaction of ‘floating_point<T>’ [with T = int]
:: /usr/include/c++/11/concepts:109:30: note: the expression ‘is_floating_point_v<_Tp> [with _Tp = int]’ evaluated to ‘false’
::   109 |     concept floating_point = is_floating_point_v<_Tp>;
::       |                              ^~~~~~~~~~~~~~~~~~~~~~~~
:: In file included from /root/parts/freecad/src/src/Mod/TechDraw/Gui/CommandExtensionDims.cpp:36:
:: /root/parts/freecad/src/src/Base/Tools.h:160:13: note: candidate: ‘template<class T>  requires (is_arithmetic_v<T>) && !(floating_point<T>) constexpr T Base::toDegrees(std::type_identity_t<T>)’
::   160 | constexpr T toDegrees(std::type_identity_t<T> radians)
::       |             ^~~~~~~~~
:: /root/parts/freecad/src/src/Base/Tools.h:160:13: note:   template argument deduction/substitution failed:
:: /root/parts/freecad/src/src/Mod/TechDraw/Gui/CommandExtensionDims.cpp:2133:44: note:   couldn’t deduce template parameter ‘T’
::  2133 |         float alpha = round(Base::toDegrees(abs(atan(dx / dy))));
::       |                             ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
:: gmake[2]: *** [src/Mod/TechDraw/Gui/CMakeFiles/TechDrawGui.dir/build.make:686: src/Mod/TechDraw/Gui/CMakeFiles/TechDrawGui.dir/CommandExtensionDims.cpp.o] Error 1

```

</details>

It seems to have been caused by https://github.com/FreeCAD/FreeCAD/pull/20747.

Note the `/snap/kde-qt5-core22-sdk/1/usr/include/x86_64-linux-gnu/qt5/*` include mentions. They are related to the snap-specifit Qt 5 build. I'm neither an expert on CMake or C++, but I find it strange that the `toDegrees` error, which I'd assume to be FreeCAD-specific, to leak into the Qt includes.

### Full version info

```shell
OS: Ubuntu Core 22 (ubuntu:GNOME/ubuntu/xcb)
Architecture: x86_64
Version: 1.1.0dev.41270 (Git) Snap 1393
Build date: 2025/04/14 21:58:26
Build type: Release
Branch: main
Hash: 61758e57861211f24cda27a5a08e72531c7410c9
Python 3.10.12, Qt 5.15.15, Coin 4.0.0, Vtk 9.1.0, IfcOpenShell 0.8.0, OCC 7.7.1
Stylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/Fusion
Logical DPI/Physical DPI/Pixel Ratio: 96/159.34/1
Installed mods: 
  * Assembly4 0.50.17
  * Launcher
```

### Subproject(s) affected?

Core

### Anything else?

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by hyarion**
Should fix #20820 

The problem can be seen here: https://github.com/FreeCAD/FreeCAD-snap/actions/runs/14482259726/job/40621422608#step:3:9555
```
:: /root/parts/freecad/src/src/Mod/TechDraw/Gui/CommandExtensionDims.cpp: In function ‘void execCreateHorizChamferDimension(Gui::Command*)’:
:: /root/parts/freecad/src/src/Mod/TechDraw/Gui/CommandExtensionDims.cpp:2065:44: error: no matching function for call to ‘toDegrees(int)’
::  2065 |         float alpha = round(Base::toDegrees(abs(atan(dy / dx))));
::       |                             ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
:: In file included from /root/parts/freecad/src/src/Mod/TechDraw/Gui/CommandExtensionDims.cpp:36:
:: /root/parts/freecad/src/src/Base/Tools.h:151:13: note: candidate: ‘template<class T>  requires  floating_point<T> constexpr T Base::toDegrees(T)’
::   151 | constexpr T toDegrees(T radians)
::       |             ^~~~~~~~~
:: /root/parts/freecad/src/src/Base/Tools.h:151:13: note:   template argument deduction/substitution failed:
:: /root/parts/freecad/src/src/Base/Tools.h:151:13: note: constraints not satisfied
:: In file included from /usr/include/c++/11/compare:39,
::                  from /usr/include/c++/11/bits/stl_pair.h:65,
::                  from /usr/include/c++/11/utility:70,
::                  from /snap/kde-qt5-core22-sdk/1/usr/include/x86_64-linux-gnu/qt5/QtCore/qglobal.h:47,
::                  from /snap/kde-qt5-core22-sdk/1/usr/include/x86_64-linux-gnu/qt5/QtGui/qtguiglobal.h:43,
::                  from /snap/kde-qt5-core22-sdk/1/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtwidgetsglobal.h:43,
::                  from /snap/kde-qt5-core22-sdk/1/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qapplication.h:43,
::                  from /snap/kde-qt5-core22-sdk/1/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QApplication:1,
::                  from /root/parts/freecad/src/src/Mod/TechDraw/Gui/CommandExtensionDims.cpp:25:
:: /usr/include/c++/11/concepts: In substitution of ‘template<class T>  requires  floating_point<T> constexpr T Base::toDegrees(T) [with T = int]’:
:: /root/parts/freecad/src/src/Mod/TechDraw/Gui/CommandExtensionDims.cpp:2065:44:   required from here
:: /usr/include/c++/11/concepts:109:13:   required for the satisfaction of ‘floating_point<T>’ [with T = int]
:: /usr/include/c++/11/concepts:109:30: note: the expression ‘is_floating_point_v<_Tp> [with _Tp = int]’ evaluated to ‘false’
::   109 |     concept floating_point = is_floating_point_v<_Tp>;
::       |                              ^~~~~~~~~~~~~~~~~~~~~~~~
:: In file included from /root/parts/freecad/src/src/Mod/TechDraw/Gui/CommandExtensionDims.cpp:36:
:: /root/parts/freecad/src/src/Base/Tools.h:160:13: note: candidate: ‘template<class T>  requires (is_arithmetic_v<T>) && !(floating_point<T>) constexpr T Base::toDegrees(std::type_identity_t<T>)’
::   160 | constexpr T toDegrees(std::type_identity_t<T> radians)
::       |             ^~~~~~~~~
:: /root/parts/freecad/src/src/Base/Tools.h:160:13: note:   template argument deduction/substitution failed:
:: /root/parts/freecad/src/src/Mod/TechDraw/Gui/CommandExtensionDims.cpp:2065:44: note:   couldn’t deduce template parameter ‘T’
::  2065 |         float alpha = round(Base::toDegrees(abs(atan(dy / dx))));
::       |                             ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
:: /root/parts/freecad/src/src/Mod/TechDraw/Gui/CommandExtensionDims.cpp: In function ‘void execCreateVertChamferDimension(Gui::Command*)’:
:: /root/parts/freecad/src/src/Mod/TechDraw/Gui/CommandExtensionDims.cpp:2133:44: error: no matching function for call to ‘toDegrees(int)’
::  2133 |         float alpha = round(Base::toDegrees(abs(atan(dx / dy))));
::       |                             ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
:: In file included from /root/parts/freecad/src/src/Mod/TechDraw/Gui/CommandExtensionDims.cpp:36:
:: /root/parts/freecad/src/src/Base/Tools.h:151:13: note: candidate: ‘template<class T>  requires  floating_point<T> constexpr T Base::toDegrees(T)’
::   151 | constexpr T toDegrees(T radians)
::       |             ^~~~~~~~~
:: /root/parts/freecad/src/src/Base/Tools.h:151:13: note:   template argument deduction/substitution failed:
:: /root/parts/freecad/src/src/Base/Tools.h:151:13: note: constraints not satisfied
:: In file included from /usr/include/c++/11/compare:39,
::                  from /usr/include/c++/11/bits/stl_pair.h:65,
::                  from /usr/include/c++/11/utility:70,
::                  from /snap/kde-qt5-core22-sdk/1/usr/include/x86_64-linux-gnu/qt5/QtCore/qglobal.h:47,
::                  from /snap/kde-qt5-core22-sdk/1/usr/include/x86_64-linux-gnu/qt5/QtGui/qtguiglobal.h:43,
::                  from /snap/kde-qt5-core22-sdk/1/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtwidgetsglobal.h:43,
::                  from /snap/kde-qt5-core22-sdk/1/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qapplication.h:43,
::                  from /snap/kde-qt5-core22-sdk/1/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QApplication:1,
::                  from /root/parts/freecad/src/src/Mod/TechDraw/Gui/CommandExtensionDims.cpp:25:
:: /usr/include/c++/11/concepts: In substitution of ‘template<class T>  requires  floating_point<T> constexpr T Base::toDegrees(T) [with T = int]’:
:: /root/parts/freecad/src/src/Mod/TechDraw/Gui/CommandExtensionDims.cpp:2133:44:   required from here
:: /usr/include/c++/11/concepts:109:13:   required for the satisfaction of ‘floating_point<T>’ [with T = int]
:: /usr/include/c++/11/concepts:109:30: note: the expression ‘is_floating_point_v<_Tp> [with _Tp = int]’ evaluated to ‘false’
::   109 |     concept floating_point = is_floating_point_v<_Tp>;
::       |                              ^~~~~~~~~~~~~~~~~~~~~~~~
:: In file included from /root/parts/freecad/src/src/Mod/TechDraw/Gui/CommandExtensionDims.cpp:36:
:: /root/parts/freecad/src/src/Base/Tools.h:160:13: note: candidate: ‘template<class T>  requires (is_arithmetic_v<T>) && !(floating_point<T>) constexpr T Base::toDegrees(std::type_identity_t<T>)’
::   160 | constexpr T toDegrees(std::type_identity_t<T> radians)
::       |             ^~~~~~~~~
:: /root/parts/freecad/src/src/Base/Tools.h:160:13: note:   template argument deduction/substitution failed:
:: /root/parts/freecad/src/src/Mod/TechDraw/Gui/CommandExtensionDims.cpp:2133:44: note:   couldn’t deduce template parameter ‘T’
::  2133 |         float alpha = round(Base::toDegrees(abs(atan(dx / dy))));
::       |                             ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
```

Specifying type for abs should help it finding which type to use. I put it there instead of in toDegrees to make sure it isn't using integer math in abs.
This problem is most likely due to an old compiler in snap but it doesn't hurt being explicit.

### CODE REVIEW

**Comment by furgo16** [comment]
Thanks. Test build running at https://github.com/FreeCAD/FreeCAD-snap/actions/runs/14493961899

**Comment by furgo16** [comment]
@kadet1090 @hyarion I've just checked the build I started at https://github.com/FreeCAD/FreeCAD/pull/20823#issuecomment-2809604020 - it failed.

https://github.com/FreeCAD/FreeCAD-snap/actions/runs/14493961899/job/40656794826#step:3:9530 => are there more locations where the fix need to be applied?
