### ISSUE TITLE
Regression: Start: Compilation (likely?) fails on MSVC with FREECAD_USE_PCH=ON

### ISSUE THREAD

**Issue by AIRCAP** [FreeCAD/FreeCAD#17257]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

MSVC builds use the FREECAD_USE_PCH feature, where headers are included through PreCompiled.h.

Compilation through PreCompiled.h  can be partially tested under linux by supplying the flag

`cmake -DFREECAD_USE_PCH=ON ...`

even though the headers won't actually be precompiled separately, they are included through the same mechanism.

This still worked in main last week. This week it doesn't anymore

Error is:

```
~/src/FreeCAD/src/Mod/Start/Gui/StartView.cpp: In member function ‘void StartGui::StartView::fileCardSelected(const QModelIndex&)’:
~/src/FreeCAD/src/Mod/Start/Gui/StartView.cpp:445:13: error: ‘QMessageBox’ has not been declared
  445 |             QMessageBox::critical(Gui::getMainWindow(),
      |             ^~~~~~~~~~~
make[2]: *** [src/Mod/Start/Gui/CMakeFiles/StartGui.dir/build.make:423: src/Mod/Start/Gui/CMakeFiles/StartGui.dir/StartView.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:7827: src/Mod/Start/Gui/CMakeFiles/StartGui.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

```

this inhibits testing of precompiled header (PCH) compilation on linux

it also likely inhibits compilation on MSVC where this feature is needed, although I cannot test that since I don't have MSVC

### Full version info

```shell
branch main, gid ID facd8ca6e0303cf96297a7a7398185770c1a1e0b
```

### Subproject(s) affected?

Other (specify in description)

### Anything else?

Filename suggests its a recent change in the Startpage (src/Mod/Start)

steps to reproduce

1. cmake with -DFREECAD_USE_PCH=ON
2. make
3. unsuccesful compilation

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AIRCAP** [comment]
would it be possible to add compilation with FREECAD_USE_PCH (or even MSVC) to the CI to throw an error if things like this happen?

**Comment by AIRCAP** [comment]
confirmed fixed
