### ISSUE TITLE
Packaging: Vendored `salomesmesh` does not compile with Netgen 6.2.2606

### ISSUE THREAD

**Issue by vovodroid** [FreeCAD/FreeCAD#32105]
### Problem description

There is an error:

`FreeCAD\FreeCAD\src\3rdParty\salomesmesh\src\NETGENPlugin\NETGENPlugin_Mesher.cpp(928,14): error C2248: 'netgen::Segment::epgeominfo': cannot access private member declared in class 'netgen::Segment'
    FreeCad\LibPack-26.3.0-v3.5.4-x64-Release\include\meshing\meshtype.hpp(1312,21):`

```
          // node param on curve
          seg.epgeominfo[ 0 ].dist = p1.param;
          seg.epgeominfo[ 1 ].dist = p2.param;
          // uv on face
          seg.epgeominfo[ 0 ].u = p1.u;
          seg.epgeominfo[ 0 ].v = p1.v;
          seg.epgeominfo[ 1 ].u = p2.u;
          seg.epgeominfo[ 1 ].v = p2.v;

```

### Workbench affected?

None

### Steps to reproduce

Build with LibPack 3.4.3 in VisualStudio and Cmake

### Expected behavior

Build works.

### Actual behavior

Build fails.

### Development version About Info (in Safe Mode)

```shell
Latest main branch
```

### Last known good version (optional)

```shell

```

**Comment by maxwxyz** [comment]
@chennes FYI

**Comment by coldtobi** [comment]
I'm seeing that also on Debian - I assume this is due to a change in netgen 2606, possible this changeset: https://github.com/NGSolve/netgen/commit/074bc99a7c4ae247d8afb9aa60c4c436d99621b7

**Comment by coldtobi** [comment]
In the hope this helps a bit, this is a partial fix to the complie issue in NetGentPlugin_Mesher.cpp:

partial, as I have no idea how to use seg.si and what to do with edgenr

```
--- a/src/3rdParty/salomesmesh/src/NETGENPlugin/NETGENPlugin_Mesher.cpp
+++ b/src/3rdParty/salomesmesh/src/NETGENPlugin/NETGENPlugin_Mesher.cpp
@@ -917,13 +917,13 @@
           seg[0] = prevNgId;
           seg[1] = prevNgId = ngNodeId( p2.node, ngMesh, nodeNgIdMap );
           // node param on curve
-          seg.epgeominfo[ 0 ].dist = p1.param;
-          seg.epgeominfo[ 1 ].dist = p2.param;
+          seg.EPGeomInfo( 0 ).dist = p1.param;
+          seg.EPGeomInfo( 1 ).dist = p2.param;
           // uv on face
-          seg.epgeominfo[ 0 ].u = p1.u;
-          seg.epgeominfo[ 0 ].v = p1.v;
-          seg.epgeominfo[ 1 ].u = p2.u;
-          seg.epgeominfo[ 1 ].v = p2.v;
+          seg.GeomInfo( 0 ).u = p1.u;
+          seg.GeomInfo( 0 ).v = p1.v;
+          seg.GeomInfo( 1 ).u = p2.u;
+          seg.GeomInfo( 1 ).v = p2.v;
 
           //geomEdge = fSide.Edge( fSide.EdgeIndex( 0.5 * ( p1.normParam + p2.normParam )));
           //seg.epgeominfo[ 0 ].edgenr = seg.epgeominfo[ 1 ].edgenr = occgeom.emap.FindIndex( geomEdge );
@@ -951,16 +951,16 @@
           if ( isSeam )
           {
             if ( helper.GetPeriodicIndex() & 1 ) {
-              seg.epgeominfo[ 0 ].u = otherSeamParam;
-              seg.epgeominfo[ 1 ].u = otherSeamParam;
-              swap (seg.epgeominfo[0].v, seg.epgeominfo[1].v);
+              seg.GeomInfo( 0 ).u = otherSeamParam;
+              seg.GeomInfo( 1 ).u = otherSeamParam;
+              swap (seg.GeomInfo(0).v, seg.GeomInfo(1).v);
             } else {
-              seg.epgeominfo[ 0 ].v = otherSeamParam;
-              seg.epgeominfo[ 1 ].v = otherSeamParam;
-              swap (seg.epgeominfo[0].u, seg.epgeominfo[1].u);
+              seg.GeomInfo( 0 ).v = otherSeamParam;
+              seg.GeomInfo( 1 ).v = otherSeamParam;
+              swap (seg.GeomInfo(0).u, seg.GeomInfo(1).u);
             }
             swap (seg[0], seg[1]);
-            swap (seg.epgeominfo[0].dist, seg.epgeominfo[1].dist);
+            swap (seg.EPGeomInfo(0).dist, seg.EPGeomInfo(1).dist);
             seg.edgenr = ngMesh.GetNSeg() + 1; // segment id
             ngMesh.AddSegment (seg);
 #ifdef DUMP_SEGMENTS
@@ -973,7 +973,7 @@
           else if ( fOri == TopAbs_INTERNAL )
           {
             swap (seg[0], seg[1]);
-            swap( seg.epgeominfo[0], seg.epgeominfo[1] );
+            swap( seg.EPGeomInfo(0), seg.EPGeomInfo(1) );
             seg.edgenr = ngMesh.GetNSeg() + 1; // segment id
             ngMesh.AddSegment (seg);
 #ifdef DUMP_SEGMENTS
@@ -1463,7 +1463,7 @@
         gp_XY uv[2];
         for ( int iEnd = 0; iEnd < 2; ++iEnd)
         {
-          uv[iEnd].SetCoord( seg.epgeominfo[iEnd].u, seg.epgeominfo[iEnd].v );
+          uv[iEnd].SetCoord( seg.GeomInfo(iEnd).u, seg.GeomInfo(iEnd).v );
           if ( ngIdLast == seg[ iEnd ] ) continue;
           dist2 = helper.ApplyIn2D(surf, uv[iEnd], vData.uv, gp_XY_Subtracted,0).SquareModulus();
           if ( dist2 < closeDist2 )
@@ -1498,7 +1498,7 @@
         gp_XY uv[2];
         for ( int iEnd = 0; iEnd < 2; ++iEnd)
         {
-          uv[iEnd].SetCoord( seg.epgeominfo[iEnd].u, seg.epgeominfo[iEnd].v );
+          uv[iEnd].SetCoord( seg.GeomInfo(iEnd).u, seg.GeomInfo(iEnd).v );
           dist2 = helper.ApplyIn2D(surf, uv[iEnd], vData.uv, gp_XY_Subtracted,0).SquareModulus();
           if ( dist2 < closeDist2 )
             vData.ngIdClose = seg[ iEnd ], vData.uvClose = uv[iEnd], closeDist2 = dist2;
@@ -1545,12 +1545,12 @@
       seg.edgenr = ngMesh.GetNSeg() + 1;// segment id
       seg.si = faceNgID;
 
-      seg.epgeominfo[ 0 ].dist = 0; // param on curve
-      seg.epgeominfo[ 0 ].u    = uvV.X();
-      seg.epgeominfo[ 0 ].v    = uvV.Y();
-      seg.epgeominfo[ 1 ].dist = 1; // param on curve
-      seg.epgeominfo[ 1 ].u    = uvP.X();
-      seg.epgeominfo[ 1 ].v    = uvP.Y();
+      seg.EPGeomInfo( 0 ).dist = 0; // param on curve
+      seg.GeomInfo( 0 ).u    = uvV.X();
+      seg.GeomInfo( 0 ).v    = uvV.Y();
+      seg.EPGeomInfo( 1 ).dist = 1; // param on curve
+      seg.GeomInfo( 1 ).u    = uvP.X();
+      seg.GeomInfo( 1 ).v    = uvP.Y();
 
 //       seg.epgeominfo[ 0 ].edgenr = 10; //  = geom.emap.FindIndex(edge);
 //       seg.epgeominfo[ 1 ].edgenr = 10; //  = geom.emap.FindIndex(edge);
@@ -1559,7 +1559,7 @@
 
       // add reverse segment
       swap (seg[0], seg[1]);
-      swap( seg.epgeominfo[0], seg.epgeominfo[1] );
+      swap( seg.EPGeomInfo(0), seg.EPGeomInfo(1) );
       seg.edgenr = ngMesh.GetNSeg() + 1; // segment id
       ngMesh.AddSegment (seg);
     }
@@ -1937,9 +1937,9 @@
       {
         const UVPtStruct& pnt = uvPtVec[ i + iEnd ];
 
-        seg.epgeominfo[ iEnd ].dist = pnt.param; // param on curve
-        seg.epgeominfo[ iEnd ].u    = pnt.u;
-        seg.epgeominfo[ iEnd ].v    = pnt.v;
+        seg.EPGeomInfo( iEnd ).dist = pnt.param; // param on curve
+        seg.GeomInfo( iEnd ).u    = pnt.u;
+        seg.GeomInfo( iEnd ).v    = pnt.v;
 
         // find out edge id and node parameter on edge
         onVertex = ( pnt.normParam + 1e-10 > vertexNormPar );
@@ -1979,7 +1979,7 @@
       if ( isInternalWire )
       {
         swap (seg[0], seg[1]);
-        swap( seg.epgeominfo[0], seg.epgeominfo[1] );
+        swap( seg.EPGeomInfo(0), seg.EPGeomInfo(1) );
         seg.edgenr = ngMesh.GetNSeg() + 1; // segment id
         ngMesh.AddSegment (seg);
       }
@@ -2124,7 +2124,7 @@
   {
     const netgen::Segment& seg = ngMesh.LineSegment(i);
     TopoDS_Edge aEdge;
-    int pinds[3] = { seg.pnums[0], seg.pnums[1], seg.pnums[2] };
+    int pinds[3] = { seg[0], seg[1], seg[2] };
     int nbp = 0;
     double param2 = 0;
     for (int j=0; j < 3; ++j)
@@ -2142,7 +2142,7 @@
           if (aGeomEdgeInd > 0 && aGeomEdgeInd <= occgeo.emap.Extent())
             aEdge = TopoDS::Edge(occgeo.emap(aGeomEdgeInd));
         }
-        param = seg.epgeominfo[j].dist;
+        param = seg.EPGeomInfo(j).dist;
         param2 += param;
       }
       else // middle point
```

**Comment by stefano2734** [comment]
Why 26.06 in libpack?
Latest today in GitHub at netgen is 26.04.
https://github.com/NGSolve/netgen/releases/tag/v6.2.2604

**Comment by vovodroid** [comment]
LibPack release says `netgen 6.2.2604`

**Comment by coldtobi** [comment]
upstream tagged it as https://github.com/NGSolve/netgen/releases/tag/v6.2.2606

**Comment by stefano2734** [comment]
You should sent this issue also to FreeCAD  libpack.

**Comment by stefano2734** [comment]
It is a rollback of netgen in 3.5.4.
https://github.com/FreeCAD/FreeCAD-LibPack/pull/99

So you should download and see again.

**Comment by coldtobi** [comment]
should we have an dedicated issue for tracking, as FreeCAD will needs updating to be compatible with 2606?

**Comment by francesco-ballarin** [comment]
> Why 26.06 in libpack? Latest today in GitHub at netgen is 26.04. https://github.com/NGSolve/netgen/releases/tag/v6.2.2604

See https://github.com/NGSolve/netgen/tags, there are releases 6.2.2605 and 6.2.2606. 

I believe you should consider them as legitimate releases, even though they not appear to have an associated description in the "Releases" page.
My reasoning is that there are corresponding tags on https://github.com/NGSolve/ngsolve/tags , and I can't imagine them having made *twice* the mistake of incorrectly tagging. It's more reasonable to imagine that they forgot to write the release description, especially considering that (to my knowleddge) the development of netgen and ngsolve actually happens on a gitlab instance, and the one on github is just a mirror.


(coming here from the issue open on Debian as well, thanks @coldtobi )

**Comment by chennes** [comment]
I've just renamed this issue, we can use it as the tracking issue. I also released an update to the Libpack that rolls this back to the 2604 release so that we can get back to compiling (the point of that LibPack was to get OCCT 8.0.1 into people's hands, I don't want to block on the netgen update).

**Comment by coldtobi** [comment]
@chennes typo: 2606 is the culprit, 2604 is fine.

**Comment by luzpaz** [comment]
~~Is this Windows OS exclusive ?~~  
Apologies, I missed that it was reproducible on Debian Linux (https://github.com/FreeCAD/FreeCAD/issues/32105#issuecomment-5380857192)

**Comment by stefano2734** [comment]
Libpack 3.5.5 with actual occt 8.0.1 is available.
Netgen is,here at previous level to avoid problems in old messages here.
So the workaround again is 2604 at netgen.

Label workaround with libpack 3.5.5 is possible

**Comment by maxwxyz** [comment]
@adrianinsaval @chennes FYI
