### PR TITLE
CMake: Cleanup targets with transitive dependencies

### PR DESCRIPTION
**Pull request by tritao**
~700 lines removed :cat:

### CODE REVIEW

**Comment by benj5378** [comment]
This might solve the CMake issue in #19762

**Comment by benj5378** [comment]
@tritao

Windows non-Pixi:
```
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.43.34808\bin\HostX64\x64\link.exe /ERRORREPORT:QUEUE /OUT:"C:\FC\build\release\Mod\Material\Materials.pyd" /INCREMENTAL:NO /NOLOGO /LIBPATH:C:/FC/libpack/lib /LIBPATH:C:/FC/libpack/lib/Release ..\..\..\App\Release\FreeCADApp.lib C:\FC\libpack\lib\Qt6Concurrent.lib "C:\FC\libpack\lib\yaml-cpp.lib" ..\..\..\Base\Release\FreeCADBase.lib "C:\FC\libpack\lib\xerces-c_3.lib" C:\FC\libpack\lib\zlib.lib MSVCRT.lib MSVCPRT.lib Rpcrt4.lib version.lib vcruntime.lib ucrt.lib concrt.lib C:\FC\libpack\bin\libs\python312.lib "C:\FC\libpack\lib\boost_program_options-vc143-mt-x64-1_86.lib" "C:\FC\libpack\lib\boost_regex-vc143-mt-x64-1_86.lib" "C:\FC\libpack\lib\boost_system-vc143-mt-x64-1_86.lib" "C:\FC\libpack\lib\boost_thread-vc143-mt-x64-1_86.lib" "C:\FC\libpack\lib\boost_chrono-vc143-mt-x64-1_86.lib" "C:\FC\libpack\lib\boost_date_time-vc143-mt-x64-1_86.lib" C:\FC\libpack\lib\fmt.lib C:\FC\libpack\lib\Qt6Xml.lib C:\FC\libpack\lib\Qt6Core.lib mpr.lib userenv.lib kernel32.lib user32.lib gdi32.lib winspool.lib SHFolder.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib winmm.lib comsupp.lib Ws2_32.lib dbghelp.lib /NODEFAULTLIB /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:"C:/FC/build/release/Mod/Material/Materials.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/FC/build/release/src/Mod/Material/App/Release/Materials.lib" /MACHINE:X64  /machine:x64 /DLL Materials.dir\Release\Array2DPyImp.obj
```

Windows Pixi:
```
C:\PROGRA~1\MICROS~2\2022\ENTERP~1\VC\Tools\MSVC\1429~1.301\bin\HostX64\x64\link.exe /nologo @CMakeFiles\Part.rsp /out:Mod\Part\Part.pyd /implib:src\Mod\Part\App\Part.lib /pdb:Mod\Part\Part.pdb /dll /version:0.0 /machine:x64 -Wl,-defaultlib:D:/a/FreeCAD/FreeCAD/.pixi/envs/default/lib/clang/19/lib/windows/clang_rt.builtins-x86_64.lib /NODEFAULTLIB /INCREMENTAL:NO /MANIFEST:EMBED,ID=2
```

**Comment by benj5378** [comment]
@tritao why are PyCXX, boost, and more only included in Base and not in the respective modules where it is also used?

**Comment by benj5378** [comment]
> > @tritao why are PyCXX, boost, and more only included in Base and not in the respective modules where it is also used?
> 
> Because everything else uses Base right?

Not untrue... though it might mean they have to be added back to the modules, if they are one day removed from base.

It's like C++ includes, we could remove all that are already used in Base... but if removed from Base, one has to go arouns all the files that previously needed the implicit include.

**Review by benj5378 — APPROVED** [review]

**Comment by aprospero** [comment]
Did I miss anything? I guess i did something stupid but am I the only one whose build is broken after this merge? 

I bisected to this MR. From here on I get errors that seem to be associated with include order changes and its unwanted sideeffects. Unfortunately I don't have the time to sort it out in detail.

Here are some first lines from the [error reports](https://github.com/user-attachments/files/19495509/FC-MR19899-build_error.log).


> In file included from /usr/include/python3.10/CXX/Objects.hxx:42,
>                  from /project/git/FreeCAD/src/App/Document.h:26,
>                  from /project/git/FreeCAD/src/Gui/Application.cpp:48:
> /usr/include/python3.10/CXX/Python3/Objects.hxx:1325:21: error: expected unqualified-id before ‘const’
>  1325 |         SeqBase<T>( const Object &ob )
>       |                     ^~~~~
> /usr/include/python3.10/CXX/Python3/Objects.hxx:1325:20: error: expected ‘)’ before ‘const’
>  1325 |         SeqBase<T>( const Object &ob )
>       |                   ~^~~~~~
>       |                    )
> In file included from /usr/include/python3.10/CXX/Objects.hxx:42,
>                  from /project/git/FreeCAD/src/App/Document.h:26,
>                  from /project/git/FreeCAD/src/Gui/Application.cpp:48:
> /usr/include/python3.10/CXX/Python3/Objects.hxx: In constructor ‘Py::Bytes::Bytes(const Py::Object&)’:
> /usr/include/python3.10/CXX/Python3/Objects.hxx:1855:29: error: no matching function for call to ‘Py::SeqBase<Py::Byte>::SeqBase(const Py::Object&)’
>  1855 |         : SeqBase<Byte>( ob )
>       |                             ^


Any advice would be really appreciated!

  Thanks in advance

**Comment by aprospero** [comment]
> 
> So I am not sure why it's not being picked up first.
> 
> Can you run `make VERBOSE=1` and paste the GCC command line invocation that emits the error?

Sure, here you go:

```
[ 14%] Building CXX object src/Gui/CMakeFiles/FreeCADGui.dir/Application.cpp.o
cd /project/git/FreeCAD/build/src/Gui && /usr/bin/c++ -DBOOST_ALL_NO_LIB -DBOOST_ATOMIC_DYN_LINK -DBOOST_DATE_TIME_DYN_LINK -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_REGEX_DYN_LINK -DBOOST_SYSTEM_DYN_LINK -DBOOST_THREAD_DYN_LINK -DBUILD_ADDONMGR -DFreeCADGui_EXPORTS -DHAVE_CONFIG_H -DHAVE_PYSIDE2 -DHAVE_SHIBOKEN2 -DPYCXX_6_2_COMPATIBILITY -DPYSIDE_QML_SUPPORT=1 -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_NO_KEYWORDS -DQT_OPENGL_LIB -DQT_PRINTSUPPORT_LIB -DQT_SVG_LIB -DQT_UITOOLS_LIB -DQT_WIDGETS_LIB -DQT_XML_LIB -DSPNAV_FOUND -D_OCC64 -D_USE_3DCONNEXION_SDK -I/project/git/FreeCAD/build/src/Gui/FreeCADGui_autogen/include -I/project/git/FreeCAD/build -I/project/git/FreeCAD/build/src -I/project/git/FreeCAD/src -I/project/git/FreeCAD/src/Gui -I/project/git/FreeCAD/src/Gui/Quarter -I/project/git/FreeCAD/src/Gui/PreferencePages -I/project/git/FreeCAD/src/Gui/Selection -I/project/git/FreeCAD/build/src/Gui -I/project/git/FreeCAD/src/Gui/.. -I/project/git/FreeCAD/build/src/Gui/.. -I/project/git/FreeCAD/build/src/Gui/Language -I/project/git/FreeCAD/build/src/Gui/propertyeditor -I/project/git/FreeCAD/build/src/Gui/TaskView -I/project/git/FreeCAD/build/src/Gui/Quarter -I/project/git/FreeCAD/build/src/Gui/DAGView -I/project/git/FreeCAD/build/_deps/fmt-src/include -isystem /usr/include/eigen3 -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -isystem /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtOpenGL -isystem /usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -isystem /usr/include/x86_64-linux-gnu/qt5/QtSvg -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtUiTools -isystem /usr/include/x86_64-linux-gnu/qt5/QtXml -isystem /usr/lib/../include/shiboken2 -isystem /usr/include/python3.10 -isystem /usr/lib/../include/PySide2 -isystem /usr/lib/../include/PySide2/QtCore -isystem /usr/lib/../include/PySide2/QtGui -isystem /usr/lib/../include/PySide2/QtWidgets -isystem /project/git/FreeCAD/src/3rdParty/PyCXX -isystem /project/git/FreeCAD/src/3rdParty -Wall -Wextra -Wno-write-strings -fdiagnostics-color  -fPIC -I/usr/include/hdf5/openmpi -I/usr/lib/x86_64-linux-gnu/openmpi/include -I/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi -fPIC -std=gnu++20 -MD -MT src/Gui/CMakeFiles/FreeCADGui.dir/Application.cpp.o -MF CMakeFiles/FreeCADGui.dir/Application.cpp.o.d -o CMakeFiles/FreeCADGui.dir/Application.cpp.o -c /project/git/FreeCAD/src/Gui/Application.cpp
```

**Comment by aprospero** [comment]
Thanks again for caring! Please have some patience, I'm AFK. I'll get to it as soon as possible.

**Comment by aprospero** [comment]
Good morning,

unfortunately the patch doesn't solve the problem.

Here's the compiler call:
```
cd /home/tidy/project/git/FreeCAD/build/src/Gui && /usr/bin/c++ -DBOOST_ALL_NO_LIB -DBOOST_ATOMIC_DYN_LINK -DBOOST_DATE_TIME_DYN_LINK -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_REGEX_DYN_LINK -DBOOST_SYSTEM_DYN_LINK -DBOOST_THREAD_DYN_LINK -DBUILD_ADDONMGR -DFreeCADGui_EXPORTS -DHAVE_CONFIG_H -DHAVE_PYSIDE2 -DHAVE_SHIBOKEN2 -DPYCXX_6_2_COMPATIBILITY -DPYSIDE_QML_SUPPORT=1 -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_NO_KEYWORDS -DQT_OPENGL_LIB -DQT_PRINTSUPPORT_LIB -DQT_SVG_LIB -DQT_UITOOLS_LIB -DQT_WIDGETS_LIB -DQT_XML_LIB -DSPNAV_FOUND -D_OCC64 -D_USE_3DCONNEXION_SDK -I/home/tidy/project/git/FreeCAD/build/src/Gui/FreeCADGui_autogen/include -I/home/tidy/project/git/FreeCAD/build -I/home/tidy/project/git/FreeCAD/build/src -I/home/tidy/project/git/FreeCAD/src -I/home/tidy/project/git/FreeCAD/src/Gui -I/home/tidy/project/git/FreeCAD/src/Gui/Quarter -I/home/tidy/project/git/FreeCAD/src/Gui/PreferencePages -I/home/tidy/project/git/FreeCAD/src/Gui/Selection -I/home/tidy/project/git/FreeCAD/build/src/Gui -I/home/tidy/project/git/FreeCAD/src/Gui/.. -I/home/tidy/project/git/FreeCAD/build/src/Gui/.. -I/home/tidy/project/git/FreeCAD/build/src/Gui/Language -I/home/tidy/project/git/FreeCAD/build/src/Gui/propertyeditor -I/home/tidy/project/git/FreeCAD/build/src/Gui/TaskView -I/home/tidy/project/git/FreeCAD/build/src/Gui/Quarter -I/home/tidy/project/git/FreeCAD/build/src/Gui/DAGView -I/home/tidy/project/git/FreeCAD/build/_deps/fmt-src/include -isystem /usr/include/eigen3 -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -isystem /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtOpenGL -isystem /usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -isystem /usr/include/x86_64-linux-gnu/qt5/QtSvg -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtUiTools -isystem /usr/include/x86_64-linux-gnu/qt5/QtXml -isystem /usr/lib/../include/shiboken2 -isystem /usr/include/python3.10 -isystem /usr/lib/../include/PySide2 -isystem /usr/lib/../include/PySide2/QtCore -isystem /usr/lib/../include/PySide2/QtGui -isystem /usr/lib/../include/PySide2/QtWidgets -isystem /home/tidy/project/git/FreeCAD/src/3rdParty/PyCXX -isystem /home/tidy/project/git/FreeCAD/src/3rdParty -Wall -Wextra -Wno-write-strings -fdiagnostics-color  -fPIC -I/usr/include/hdf5/openmpi -I/usr/lib/x86_64-linux-gnu/openmpi/include -I/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi -fPIC -std=gnu++20 -MD -MT src/Gui/CMakeFiles/FreeCADGui.dir/Application.cpp.o -MF CMakeFiles/FreeCADGui.dir/Application.cpp.o.d -o CMakeFiles/FreeCADGui.dir/Application.cpp.o -c /home/tidy/project/git/FreeCAD/src/Gui/Application.cpp
```
And for completeness here's the [FC_patched-error.log](https://github.com/user-attachments/files/19524694/FC_patched-error.log):

**Comment by aprospero** [comment]
Nevermind, I resorted to docker.

**Comment by benj5378** [comment]
@tritao is this to any help? https://stackoverflow.com/questions/3016448/how-can-i-get-cmake-to-find-my-alternative-boost-installation
