### PR TITLE
TechDraw: fix Qt5 compatibility

### LINKED ISSUE #27248: [Compilation Lost compatibility with Qt5
### Problem description

Cannot build with Qt5.15 due to the use of `QList.emplace_back()` in TechDraw:
```
[ 85%] Building CXX object src/Mod/TechDraw/Gui/CMakeFiles/TechDrawGui.dir/QGIProjGroup.cpp.o
/home/gael/04-sources/freecad/FreeCAD/src/Mod/TechDraw/Gui/QGIProjGroup.cpp: In member function ‘QList<TechDrawGui::QGIViewPart*> TechDrawGui::QGIProjGroup::secondaryQViews() const’:
/home/gael/04-sources/freecad/FreeCAD/src/Mod/TechDraw/Gui/QGIProjGroup.cpp:249:16: error: ‘class QList<TechDrawGui::QGIViewPart*>’ has no member named ‘emplace_back’
  249 |         result.emplace_back(qview);
      |                ^~~~~~~~~~~~
```

According to https://doc.qt.io/archives/qt-5.15/qlist.html the method is not implemented.

### Workbench affected?

TechDraw

### Steps to reproduce

1. `make`

### Expected behavior

Should compile with Qt5.15.

### Actual behavior

Cf. above error.

### Development version About Info (in Safe Mode)

```shell
The culprit is commit fd014445fbfb.
```

### Last known good version (optional)

```shell
Commit 5d4495785b72?
```

### PR DESCRIPTION
**Pull request by Lgt2x**
emplace_back was added in Qt6, replace by append which does the same thing.

## Issues

Fix #27248

### CODE REVIEW

**Comment by maxwxyz** [comment]
I thought we've finally dropped Qt5 support @kadet1090

**Comment by Lgt2x** [comment]
@maxwxyz see discussion over at the linked issue

**Comment by xtemp09** [comment]
Who changes the version of the framework before the release? Of course, the developers of _FreeCAD_!


Oh… wait… they are simply "not making an effort to ensure that it compiles on Qt5 anymore"


I laughed my <s>ass</s> head out when I read this.

**Comment by freecad-ci-runner** [comment]
Backport failed for `releases/FreeCAD-1-1`, because it was unable to cherry-pick the commit(s).

Please cherry-pick the changes locally and resolve any conflicts.
```bash
git fetch origin releases/FreeCAD-1-1
git worktree add -d .worktree/backport-27253-to-releases/FreeCAD-1-1 origin/releases/FreeCAD-1-1
cd .worktree/backport-27253-to-releases/FreeCAD-1-1
git switch --create backport-27253-to-releases/FreeCAD-1-1
git cherry-pick -x 2dcc35153225ea3bbccb9314b81c28c499c6af45
```

**Comment by xtemp09** [comment]
If only there was a roadmap, clearly stating:


```
1.0 Qt 5&6
1.1 Qt 6
1.2 Qt 6&7
```


At least, this is something understandable. But the team of developers and maintainers simply stopped putting any effort if _FreeCAD_ compiles.

**Comment by Lgt2x** [comment]
@xtemp09 if you looked at the release branch for 2 seconds before posting a snarky comment, you'd realize that 1.1 branch still builds with qt5 and Ubuntu 22 https://github.com/FreeCAD/FreeCAD/blob/releases/FreeCAD-1-1/.github/workflows/sub_buildUbuntu.yml

**Comment by xtemp09** [comment]
@Lgt2x, this yml makes no sense to me.

**Comment by Lgt2x** [comment]
This means that the CI for 1.1 still uses Qt5, because PR https://github.com/FreeCAD/FreeCAD/pull/26894 was not backported to release. Qt5 is not dropped for 1.1, even though the forum post does not specify it.

**Comment by xtemp09** [comment]
@Lgt2x, does this commit go to the master branch or `releases/FreeCAD-1-1`?


From what I see, it went to `FreeCAD:main` and failed for `releases/FreeCAD-1-1`


I mean [this post](https://github.com/FreeCAD/FreeCAD/pull/27253#issuecomment-3828228427).

**Comment by kadet1090** [comment]
@xtemp09 please remain civil, making such snarky comments does not help anyone. 

Your comment that dropping support for major library version right before release is not something that should happen is of course valid. As mentioned by @Lgt2x the PR that breaks compatibility was not merged into 1.1 - so the accusation is simply wrong. The support is broken for the NEXT release of FreeCAD. 

We also try to establish rules on how and when to update library versions here: https://github.com/FreeCAD/FreeCAD-Enhancement-Proposals/pull/13 feel free to make suggestions here so we can establish something that we all agree about.

**Comment by Lgt2x** [comment]
This PR should not have been tagged for backport because the fixed code is not on release branch

**Comment by kadet1090** [comment]
Yes, @maxwxyz simply have not noticed that the breaking change was not introduced into 1.1 and I have not noticed that it is marked for 1.1 too.
