### ISSUE TITLE
Part: Regression on slicing of slice

### ISSUE THREAD

**Issue by theosib** [FreeCAD/FreeCAD#22827]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Problem description

I have a design that loaded up fine in older versions of FreeCAD but is now broken. I had shared it on Discord, and one of the devs says it appears to be a regression. Basically, I have sliced an object based on a manifold, and then I sliced it again based on another manifold. (He said, "it doesnt want to slice a folder.") This was not a problem before but seems to be broken now, so I figured I'd share it as an example.

[turret candle bigger 4.FCStd.zip](https://github.com/user-attachments/files/21496655/turret.candle.bigger.4.FCStd.zip)

Also, this might be tangentially related to my other report on slicing of slicing, https://github.com/issues/created?issue=FreeCAD%7CFreeCAD%7C19873.

### Full version info

```shell
OS: macOS 15.5
Architecture: arm64
Version: 1.1.0dev.14555 (Git shallow)
Build date: 2025/07/25 22:54:43
Build type: Release
Branch: main
Hash: ce9bc869086159a8655e262500f00bd39cb4d860
Python 3.11.13, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, IfcOpenShell 0.8.0, OCC 7.8.1
Locale: English/United States (en_US) [ OS: English/United States (en_US) ]
Navigation Style/Orbit Style/Rotation Mode: Touchpad/Trackball/Drag at cursor
Stylesheet/Theme/QtStyle: unset/Classic/fusion
Logical DPI/Physical DPI/Pixel Ratio: 72/127.5/2
Installed mods: 
  * TextManipulation
  * freecad.gears 1.3.0
  * Pyramids-and-Polyhedrons
  * fasteners 0.5.29
  * lattice2 1.0.0
  * Alternate_OpenSCAD 1.0.0
  * Curves 0.6.50
```

### Subproject(s) affected?

None

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by chennes** [comment]
@Syres916 do you have time to do a bisect to track this one down?

**Comment by theo-vt** [comment]
Hi hello I tried opening it in 1.02 and I get the same error as in 1.1dev "'App::DocumentObjectGroup' has no attribute 'Shape'" in which version did it previously work for you?

**Comment by FEA-eng** [comment]
> Hi hello I tried opening it in 1.02 and I get the same error as in 1.1dev "'App::DocumentObjectGroup' has no attribute 'Shape'" in which version did it previously work for you?

I have the same error message after recomputing this file in 1.1.0 dev.

```
11:26:58  <Sketch> SketchObject.cpp(9096): External geometry turret_candle_bigger#Sketch016.e3 missing reference: Common.;#4b0e:1;:G56#147ee;CMN;:H407:f,E
11:26:58  <Sketch> SketchObject.cpp(9096): External geometry turret_candle_bigger#Sketch016.e5 missing reference: Common.;#4b0e:1;:G55#147ed;CMN;:H407:f,E
11:26:58  <Sketch> SketchObject.cpp(9096): External geometry turret_candle_bigger#Sketch015.e1 missing reference: Common.;#4b0e:4;:G57#17b4e;CMN;:H407:f,E
11:26:58  <Sketch> SketchObject.cpp(9096): External geometry turret_candle_bigger#Sketch015.e5 missing reference: Common.;#4b0e:4;:G51#18a85;CMN;:H407:f,E
11:26:58  <Sketch> SketchObject.cpp(9096): External geometry turret_candle_bigger#Sketch015.e6 missing reference: Common.;#4b0e:4;:G47#1f5f5;CMN;:H407:f,E
11:26:58  <Sketch> SketchObject.cpp(9096): External geometry turret_candle_bigger#Sketch015.e7 missing reference: Common.;#4b0e:4;:G48#1f5f7;CMN;:H407:f,E
11:26:58  <Sketch> SketchObject.cpp(9096): External geometry turret_candle_bigger#Sketch017.e1 missing reference: Cut006.;#7a32:4;:G4#76df;CUT;:H42a:d,E
11:26:58  <Sketch> SketchObject.cpp(9096): External geometry turret_candle_bigger#Sketch017.e2 missing reference: Cut006.;#7a32:4;:G3#76e1;CUT;:H42a:d,E
11:26:58  <Sketch> SketchObject.cpp(9096): External geometry turret_candle_bigger#Sketch017.e17 missing reference: Cut006.;#734c:1;:M;CUT;:H42e:7,E
11:26:58  Part::FeaturePython: Link(s) to object(s) 'Fusion009' go out of the allowed scope 'Slice'. Instead, the linked object(s) reside within 'Part'.
11:26:58  pyException: Traceback (most recent call last):
  File "E:\Program Files\FreeCAD_weekly-2025.09.24-Windows-x86_64-py311\Mod\Part\BOPTools\SplitFeatures.py", line 238, in execute
    selfobj.Shape = SplitAPI.slice(selfobj.Base.Shape,
                                   ^^^^^^^^^^^^^^^^^^
<class 'AttributeError'>: 'App.DocumentObjectGroup' object has no attribute 'Shape'
11:26:58  Slice001: 'App.DocumentObjectGroup' object has no attribute 'Shape'
```

```
OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.1.0dev.14555 (Git shallow)
Build date: 2025/09/23 18:47:15
Build type: Release
Branch: main
Hash: e9ce06155d8d47aad7d6c079bfa8ba54df2b6081
Python 3.11.13, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: Polish/Poland (pl_PL)
Navigation Style/Orbit Style/Rotation Mode: CAD/Rounded Arcball/Window center
Stylesheet/Theme/QtStyle: FreeCAD.qss/FreeCAD Light/
Logical DPI/Physical DPI/Pixel Ratio: 96/90.0633/1
```

**Comment by ipatch** [comment]
i'll take a look at this after the meeting.

**Comment by ipatch** [comment]
okay just to be clear about this one. i downloaded the above file, and loaded it in both my dev build of freecad and the homebrew build of v1.0.2 of freecad (the official release of freecad). i do get different messages in the report view of freecad depending on the version.

however in both versions i have tested with i get the below error,

```
14:35:07  pyException: Traceback (most recent call last):
  File "/home/capin/homebrew/Cellar/freecad@1.0.2_py312/1.0.2/Mod/Part/BOPTools/SplitFeatures.py", line 242, in execute
    selfobj.Shape = SplitAPI.slice(selfobj.Base.Shape,
                                   ^^^^^^^^^^^^^^^^^^
<class 'AttributeError'>: 'App.DocumentObjectGroup' object has no attribute 'Shape'
14:35:07  Slice001: 'App.DocumentObjectGroup' object has no attribute 'Shape'
```

**is this an actual regression?** and if so, do i need to build a version of freecad prior to the v1.0.2 release in order to make this work? **or does the recompute task in the model fail with every version of freecad?**

and just for clarity i've attached a screenshot of what i'm seeing in the 3d viewport just to make sure we're all on the same page here.

<img width="1805" height="1633" alt="Image" src="https://github.com/user-attachments/assets/76ffd60a-d218-44bb-87f8-91c419151f0c" />

**Comment by ipatch** [comment]
i just spun up a macos Catalina vm where i had freecad 0.20 installed on it. i opened the document posted above by unzipping the document, so i ended up with the below file structure and then opened the `turret candle bigger 4.FCStd`. i got some, if not all the same errors that i got in the v1.0.2 release as well as the current dev versions in the report window, and then i chose to recompute the object i got the same error that i posted in my previous comment. and this freecad release was one that i built some time in 2021, **so i'm not exactly sure if this really is a regression, or i'm just missing something here? 😕**

<img width="3830" height="2150" alt="Image" src="https://github.com/user-attachments/assets/c73d137e-acb4-4033-88db-20ed28310c66" />

```
brewer@vmcatalina ~/d/freecad-dev> unzip turret.candle.bigger.4.FCStd.zip
Archive:  turret.candle.bigger.4.FCStd.zip
  inflating: turret candle bigger 4.FCStd
brewer@vmcatalina ~/d/freecad-dev> l
total 19280
drwxrwxr-x  4 brewer  staff   128B Oct 18 18:21 ./
drwx------+ 5 brewer  staff   160B Oct 18 18:21 ../
-rw-r--r--  1 brewer  staff   4.8M Mar  2  2025 turret candle bigger 4.FCStd
-rw-rw-r--  1 brewer  staff   4.6M Jul 29 15:11 turret.candle.bigger.4.FCStd.zip
brewer@vmcatalina ~/d/freecad-dev>
```

**Comment by chennes** [comment]
@theosib do you have a version of the file from *before* opening and re-saving with 1.1?

**Comment by mnesarco** [comment]
AFAIK this has never been supported. So I think this is not a regression.

# FreeCAD 0.21

```
OS: Linux Mint 22.2 (X-Cinnamon/cinnamon)
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 0.21.2)
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.10.13, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.6, OCC 7.6.3
Locale: English/United States (en_US)
```

Does not work. Error:

```
'App.DocumentObjectGroup' object has no attribute 'Shape'
```

<img width="969" height="371" alt="Image" src="https://github.com/user-attachments/assets/b58d0c30-23d8-4753-82b2-16d9aea9b8f7" />

# FreeCAD 0.22

```
OS: Linux Mint 22.2 (X-Cinnamon/cinnamon)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36731 (Git) AppImage
Build type: Release
Branch: main
Hash: ac1d887336826c59321352f49a195bf1ef8be2f0
Python 3.11.8, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
```

Does not work. Error:

```
'App.DocumentObjectGroup' object has no attribute 'Shape'
```

<img width="1068" height="563" alt="Image" src="https://github.com/user-attachments/assets/e77a99c0-ff45-4c2d-a995-3c63e5da9011" />

# FreeCAD 1.0.1

```
OS: Linux Mint 22.2 (X-Cinnamon/cinnamon/xcb)
Architecture: x86_64
Version: 1.0.1.39285 (Git) Conda AppImage
Build type: Release
Branch: (HEAD detached at 1.0.1)
Hash: 878f0b8c9c72c6f215833a99f2762bc3a3cf2abd
Python 3.11.12, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: unset/unset/Qt default

```

Does not work. Error:

```
'App.DocumentObjectGroup' object has no attribute 'Shape'
```

<img width="800" height="455" alt="Image" src="https://github.com/user-attachments/assets/38eaeee0-fab7-4f86-ae35-b1a2b8282187" />

# FreeCAD 1.1 main

```
OS: Linux Mint 22.2 (X-Cinnamon/cinnamon/xcb)
Architecture: x86_64
Version: 1.1.0dev.44167 (Git)
Build date: 2025/11/05 18:46:35
Build type: Unknown
Branch: main
Hash: 37af704998540fbc12facf58f1fe13f32ac1cf87
Python 3.11.13, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: English/United States (en_US)
Navigation Style/Orbit Style/Rotation Mode: Gesture/Trackball/Drag at cursor
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/
Logical DPI/Physical DPI/Pixel Ratio: 96/102.406/1
Installed mods: 
  * Vars 0.0.2.beta5
  * FreeCAD_Svg 1.0.0.dev6
  * Curves 0.6.68
  * Channels 0.1.0.dev3
  * OpenTheme 2024.9.1
  * FreeCAD_Utils 0.2.16
  * MarzWorkbench 0.1.16
```

Does not work. Error:

```
'App.DocumentObjectGroup' object has no attribute 'Shape'
```

<img width="1019" height="658" alt="Image" src="https://github.com/user-attachments/assets/cecd4af5-278a-4bf7-9428-b8e93cbcb7ba" />

**Comment by mnesarco** [comment]
LinkStage3 does not support it either:

```
OS: Linux Mint 22.2 (X-Cinnamon/cinnamon)
Word size of FreeCAD: 64-bit
Version: 2023.131.26244 +5365 (Git) AppImage
Build type: Release
Branch: LinkDaily
Hash: 73c4ca254c5de8849d104973482e98399fb24863
Python version: 3.10.8
Qt version: 5.15.4
Coin version: 4.0.1
OCC version: 7.6.3
Locale: English/United States (en_US)
```

<img width="624" height="410" alt="Image" src="https://github.com/user-attachments/assets/3a13da75-4fc4-44f2-81a4-42e34ae6d7a8" />

**Comment by mnesarco** [comment]
I didn't realize that the provided file for testing was already broken :facepalm:

**Comment by mnesarco** [comment]
# Confirmed

I created a simple file with a slice of slice in FC 0.21, everything worked. But the file is broken in 1.1.

<img width="560" height="277" alt="Image" src="https://github.com/user-attachments/assets/0fac2a35-7172-48e3-b7a7-eaea2513c85a" />
<img width="608" height="251" alt="Image" src="https://github.com/user-attachments/assets/0a78065b-60c5-49e1-927b-f3327fcac001" />


# Test file (Created and saved in 0.21
[Slice-of-Slice-021.FCStd.zip](https://github.com/user-attachments/files/23463860/Slice-of-Slice-021.FCStd.zip)

**Comment by mnesarco** [comment]
Apparently the last commit where this worked was: 7c8b9a4b2c0dfa0c7704fcbb71c282ca9925e93f

The files involved are:
- src/Mod/Part/BOPTools/SplitFeatures.py
- src/Mod/Part/BOPTools/SplitAPI.py

I am not sure yet what is the Issue in the code and I cannot continue the review today, But I will take a look again tomorrow. Or maybe someone can catch the problem.

**Comment by mnesarco** [comment]
## New information:
The file created in 0.21 worked only the first time, the recompute fails even in fc 0.21.

Same experiment in 1.1, worked first time, but recompute fails.

## My conclusion (I may be wrong)

- This is an old and active Bug
- This is not a regression (never worked or worked in ancient times pre 0.21 (unlikely))

## Steps to reporduce in any version of FreeCAD from 0.21

1. Create 3 solids (ie Cylinder Cube and Cone)
2. Make sure the three objects intersect
3. Create a "Slice Apart" using two of the three solids
4. Create a "Slice Apart" using the remaining solids and the created Slice group

Up to here everything looks good

5. Now mark the document for recompute
6. Recompute
7. Boom

## Versions pre 0.21

I have no idea and no way to build such ancient versions.

**Comment by ipatch** [comment]
i'm gunna take a look this one, as with your update instructions above i am able to reproduce with my daily dev build. 👍️

<img width="3103" height="2084" alt="Image" src="https://github.com/user-attachments/assets/cef4b9fb-d809-4a92-a5db-466d19902ed3" />

error message from the report window / panel

```
Traceback (most recent call last):
  File /opt/code/git/github/forks/freecad-git/installs/issue.tshooting.qt6.py313/Mod/Part/BOPTools/SplitFeatures.py, line 304, in execute
    [obj.Shape for obj in selfobj.Tools],
<class 'AttributeError'>: 'App.DocumentObjectGroup' object has no attribute 'Shape'
Slice001: 'App.DocumentObjectGroup' object has no attribute 'Shape'
```
