### ISSUE TITLE
Compilation error spnav_client_name on Ubuntu 22.04

### ISSUE THREAD

**Issue by FEA-eng** [FreeCAD/FreeCAD#27604]
### Area / Workbench affected

Build system / CI

### Problem description

I am getting the following error when trying to compile on my Ubuntu 22.04.5 LTS VM:

```
/home/ubuntu/Documents/freecad_fem_viz_icons/freecad-source/src/Gui/3Dconnexion/GuiNativeEventLinux.cpp: In member function ‘virtual void Gui::GuiNativeEvent::initSpaceball(QMainWindow*)’:

/home/ubuntu/Documents/freecad_fem_viz_icons/freecad-source/src/Gui/3Dconnexion/GuiNativeEventLinux.cpp:58:9: error: ‘spnav_client_name’ was not declared in this scope

   58 |         spnav_client_name("FreeCAD");

      |         ^~~~~~~~~~~~~~~~~
```

Can it be due to #27263?

### Impact

Error on compilation

### Development version (if relevant)

```shell

```

**Comment by WandererFan** [comment]
FWIW, I unchecked FREECAD_USE_3DCONNEXION_LEGACY to allow the build to proceed.  

I don't have a spacenav.

**Comment by Lgt2x** [comment]
`spnav_client_name` function was added to header by commit https://github.com/FreeSpacenav/libspnav/commit/da9c052146436758d15d9bf42f416b8336f98893 , which is part of the v1.0 release of `libspnav`. Ubuntu 22.04 [ships version v0.2.3](https://packages.ubuntu.com/source/jammy/libspnav), so this function is not present in the header. I don't know if we're supposed to support building FC master against Ubuntu 22.04, but the PR was [backported to 1.1](https://github.com/FreeCAD/FreeCAD/pull/27466). Should the backport be reverted @chennes ? We're bumping a library version requirement between RCs...
