### PR TITLE
CAM: Processor - Fix regression after #22764

### PR DESCRIPTION
**Pull request by tarman3**
Fix regression after
- #22764

Get errors if place cursor in list of post-processors in CAM Preferences

 
Screenshot_20260105_140942_lossy

```
Traceback (most recent call last):
  File "/home/user/projects/FreeCAD_build/Mod/CAM/Path/Post/Processor.py", line 112, in get_post_processor
    PostClass = getattr(module, class_name)
AttributeError: module 'KineticNCBeamicon2_post' has no attribute 'Kineticncbeamicon2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/projects/FreeCAD_build/Mod/CAM/Path/Main/Gui/PreferencesJob.py", line 294, in setProcessorListTooltip
    self.setPostProcessorTooltip(self.form.postProcessorList, item.text(), "")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/projects/FreeCAD_build/Mod/CAM/Path/Main/Gui/PreferencesJob.py", line 287, in setPostProcessorTooltip
    processor = self.getPostProcessor(name)
  File "/home/user/projects/FreeCAD_build/Mod/CAM/Path/Main/Gui/PreferencesJob.py", line 281, in getPostProcessor
    processor = PostProcessorFactory.get_post_processor(None, name)
  File "/home/user/projects/FreeCAD_build/Mod/CAM/Path/Post/Processor.py", line 117, in get_post_processor
    return WrapperPost(job, module_path, module_name)
  File "/home/user/projects/FreeCAD_build/Mod/CAM/Path/Post/Processor.py", line 537, in __init__
    super().__init__(job, tooltip=None, tooltipargs=None, units=None, *args, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/projects/FreeCAD_build/Mod/CAM/Path/Post/Processor.py", line 149, in __init__
    self._operations = getattr(job.Operations, "Group", [])
                               ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'Operations'
```

### CODE REVIEW

**Comment by tarman3** [comment]
Not for 1.1
Only 1.2

**Comment by tarman3** [comment]
Fixed by
- #26533
